; generated by a68lean compile --llvm
target triple = "arm64-apple-macosx"

@a68_line_no = external global i32
@a68_jump_flag = external global i32
@A68_BLOB = private constant [527 x i8] c"m void\0As 3c\0Am char\0Am row 1 1 2\0As \0As 616461\0As 627269616e\0As 6361726f6c\0As 64616e\0As 657665\0As 6672616e6b\0As 6772616365\0As 6865696469\0As 555042\0As 504552534f4e\0Am named 14\0Am row 1 0 15\0As 7072696e7466\0Af dig 1\0Af rep 2 0 18\0Af sign 0\0Af dig 0\0As 2e20\0Af lit 22\0Af gen 0\0Af sep\0As 2061676520\0Af lit 26\0Ak 10 19 20 21 23 24 25 27 19 20 21\0Am format\0Am int 0\0As 7072696e74\0As 6e65776c696e65\0Am file\0Am ref 33\0Am proc 0 1 34\0As 6d65616e206167653a20\0Af lit 36\0Af point\0Af nl\0Ak 9 37 19 20 21 38 21 21 25 39\0Am real 0\0As 6e616d65\0As 616765\0Am struct 2 42 3 43 30\0An 14 44\0A\00"
@A68_SRC = private constant [14 x i8] c"quicksort.a68\00"
declare void @a68rt_boot(ptr, i32, i8, i32, ptr, ptr)
@a68_nf_of_fn = internal constant [4 x ptr] [ptr null, ptr null, ptr null, ptr null]
declare i32 @a68rt_finish(i32)
declare void @a68rt_push_bool(i8, i32)
declare void @a68rt_dyop(i32, i32, i32, i32)
declare i8 @a68rt_pop_bool(i32)
declare void @a68rt_push_skip(i32, i32)
declare void @a68rt_push_real(double, i32)
declare void @a68rt_row_of(i32)
declare void @a68rt_index_error(i64, i64, i64, i32)
declare i64 @a68rt_sel_int(i32, i32, i32, i64, i64, i32, i32)
declare void @a68rt_arith_error(i32, i32)
declare void @a68rt_deref(i32)
declare void @a68rt_select(i32, i8, i32)
declare void @a68rt_slice(i32, i64, i8, i32)
declare i64 @a68rt_cell_int(i32, i32, i32)
declare void @a68rt_unite(i32, i32)
declare void @a68rt_push_format(i32, i32)
declare void @a68rt_push_builtin(i32, i32)
declare void @a68rt_set_int(i32, i32, i64, i32)
declare void @a68rt_call(i32, i32)
declare i64 @a68rt_pop_int(i32)
declare void @a68rt_monop(i32, i32, i32)
declare void @a68rt_leave(i32)
declare void @a68rt_push_cell(i32, i32, i32)
declare void @a68rt_pop(i32)
declare void @a68rt_assign(i8, i32)
declare void @a68rt_push_ref(i32, i32, i32)
declare void @a68rt_new_row(i32, i8, i32)
declare void @a68rt_push_int(i64, i32)
declare void @a68rt_collateral(i32, i8, i32, i32)
declare void @a68rt_push_undef(i32)
declare void @a68rt_push_str(i32, i32)
declare void @a68rt_store(i32, i32, i32)
declare void @a68rt_push_proc(i32, i32, i32)
declare ptr @a68rt_enter(i32, i32)
declare ptr @a68rt_enter_args(i32, i32, i32)

define void @a68_fn0() {
entry:
  %v0 = alloca ptr
  %v1 = alloca i64
  %v2 = alloca ptr
  %v3 = alloca i64
  %v4 = alloca ptr
  %v5 = alloca i64
  %v6 = alloca i1
  %v7 = alloca ptr
  %v8 = alloca i1
  %v9 = alloca i64
  %v10 = alloca i1
  %v11 = alloca ptr
  %v12 = alloca i64
  %v13 = alloca i1
  %v14 = alloca i64
  %v15 = alloca i64
  %v16 = alloca i32
  %v17 = alloca i1
  %v18 = alloca i32
  %v19 = alloca i32
  %v20 = alloca i64
  %v21 = alloca i64
  %v22 = alloca ptr
  %v23 = alloca i64
  %v24 = alloca i1
  %v25 = alloca ptr
  %v26 = alloca i1
  %v27 = alloca i64
  %v28 = alloca i1
  %v29 = alloca ptr
  %v30 = alloca i64
  %v31 = alloca i1
  %v32 = alloca i64
  %v33 = alloca i64
  %v34 = alloca i64
  %v35 = alloca i1
  %v36 = alloca i1
  %v37 = alloca i1
  %v38 = alloca i1
  %v39 = alloca i1
  %v40 = alloca i1
  %v41 = alloca i1
  %v42 = alloca ptr
  %v43 = alloca i64
  %v44 = alloca i64
  %v45 = alloca i64
  %v46 = alloca i64
  %v47 = alloca ptr
  %v48 = alloca i64
  %v49 = alloca i1
  %v50 = alloca ptr
  %v51 = alloca i1
  %v52 = alloca i64
  %v53 = alloca i1
  %v54 = alloca ptr
  %v55 = alloca i64
  %v56 = alloca i1
  %v57 = alloca i64
  %v58 = alloca i1
  %v59 = alloca i64
  %v60 = alloca i64
  %v61 = alloca i64
  %v62 = alloca i64
  %v63 = alloca i1
  %v64 = alloca i1
  %v65 = alloca i1
  %v66 = alloca i64
  %v67 = alloca i64
  %v68 = alloca i64
  %v69 = alloca ptr
  %v70 = alloca i64
  %v71 = alloca ptr
  %v72 = alloca i1
  %v73 = alloca ptr
  %v74 = alloca i64
  %v75 = alloca i1
  %v76 = alloca i64
  %v77 = alloca i64
  %v78 = alloca i64
  %v79 = alloca i1
  %v80 = alloca i64
  %v81 = alloca ptr
  %v82 = alloca i64
  %v83 = alloca i1
  %v84 = alloca i64
  %v85 = alloca i64
  %v86 = alloca i64
  %v87 = alloca i32
  %v88 = alloca i1
  %v89 = alloca i64
  %v90 = alloca i64
  %v91 = alloca ptr
  %v92 = alloca i64
  %v93 = alloca i1
  %v94 = alloca ptr
  %v95 = alloca i1
  %v96 = alloca i64
  %v97 = alloca i1
  %v98 = alloca ptr
  %v99 = alloca i64
  %v100 = alloca i1
  %v101 = alloca i64
  %v102 = alloca i1
  %v103 = alloca i64
  %v104 = alloca i64
  %v105 = alloca i64
  %v106 = alloca i64
  %v107 = alloca i1
  %v108 = alloca i1
  %v109 = alloca i1
  %v110 = alloca i64
  %v111 = alloca i64
  %v112 = alloca i64
  %v113 = alloca ptr
  %v114 = alloca i64
  %v115 = alloca ptr
  %v116 = alloca i1
  %v117 = alloca ptr
  %v118 = alloca i64
  %v119 = alloca i1
  %v120 = alloca i64
  %v121 = alloca i64
  %v122 = alloca i64
  %v123 = alloca i1
  %v124 = alloca i64
  %v125 = alloca ptr
  %v126 = alloca i64
  %v127 = alloca i1
  %v128 = alloca i64
  %v129 = alloca i64
  %v130 = alloca i64
  %v131 = alloca i64
  %v132 = alloca i32
  %v133 = alloca i1
  %v134 = alloca i64
  %v135 = alloca double
  %v136 = alloca i64
  %v137 = alloca ptr
  %v138 = alloca i64
  %v139 = alloca i1
  %v140 = alloca ptr
  %v141 = alloca i1
  %v142 = alloca i64
  %v143 = alloca i1
  %v144 = alloca ptr
  %v145 = alloca i64
  %v146 = alloca i1
  %v147 = alloca i64
  %v148 = alloca i64
  %v149 = alloca double
  %v150 = alloca double
  %v151 = alloca i32
  %v152 = alloca i1
  br label %b0
b0:
  %t0 = call ptr @a68rt_enter_args(i32 0, i32 0, i32 0)
  %t1 = call ptr @a68rt_enter(i32 4, i32 0)
  store ptr %t1, ptr %v2
  store i32 5, ptr @a68_line_no, !tbaa !16
  call void @a68rt_push_proc(i32 1, i32 4, i32 0)
  call void @a68rt_store(i32 0, i32 1, i32 0)
  store i32 17, ptr @a68_line_no, !tbaa !16
  call void @a68rt_push_proc(i32 2, i32 2, i32 0)
  call void @a68rt_store(i32 0, i32 2, i32 0)
  call void @a68rt_push_str(i32 4, i32 0)
  call void @a68rt_push_undef(i32 0)
  %t2 = zext i1 true to i8
  call void @a68rt_collateral(i32 2, i8 %t2, i32 0, i32 0)
  call void @a68rt_push_int(i64 1, i32 0)
  call void @a68rt_push_int(i64 8, i32 0)
  %t3 = zext i1 false to i8
  call void @a68rt_new_row(i32 1, i8 %t3, i32 0)
  call void @a68rt_store(i32 0, i32 0, i32 0)
  store i32 3, ptr @a68_line_no, !tbaa !16
  call void @a68rt_push_ref(i32 0, i32 0, i32 0)
  call void @a68rt_push_str(i32 5, i32 0)
  call void @a68rt_push_int(i64 36, i32 0)
  %t4 = zext i1 true to i8
  call void @a68rt_collateral(i32 2, i8 %t4, i32 0, i32 0)
  call void @a68rt_push_str(i32 6, i32 0)
  call void @a68rt_push_int(i64 29, i32 0)
  %t5 = zext i1 true to i8
  call void @a68rt_collateral(i32 2, i8 %t5, i32 0, i32 0)
  call void @a68rt_push_str(i32 7, i32 0)
  call void @a68rt_push_int(i64 52, i32 0)
  %t6 = zext i1 true to i8
  call void @a68rt_collateral(i32 2, i8 %t6, i32 0, i32 0)
  call void @a68rt_push_str(i32 8, i32 0)
  call void @a68rt_push_int(i64 41, i32 0)
  %t7 = zext i1 true to i8
  call void @a68rt_collateral(i32 2, i8 %t7, i32 0, i32 0)
  call void @a68rt_push_str(i32 9, i32 0)
  call void @a68rt_push_int(i64 29, i32 0)
  %t8 = zext i1 true to i8
  call void @a68rt_collateral(i32 2, i8 %t8, i32 0, i32 0)
  call void @a68rt_push_str(i32 10, i32 0)
  call void @a68rt_push_int(i64 63, i32 0)
  %t9 = zext i1 true to i8
  call void @a68rt_collateral(i32 2, i8 %t9, i32 0, i32 0)
  call void @a68rt_push_str(i32 11, i32 0)
  call void @a68rt_push_int(i64 45, i32 0)
  %t10 = zext i1 true to i8
  call void @a68rt_collateral(i32 2, i8 %t10, i32 0, i32 0)
  call void @a68rt_push_str(i32 12, i32 0)
  call void @a68rt_push_int(i64 33, i32 0)
  %t11 = zext i1 true to i8
  call void @a68rt_collateral(i32 2, i8 %t11, i32 0, i32 0)
  %t12 = zext i1 false to i8
  call void @a68rt_collateral(i32 8, i8 %t12, i32 1, i32 0)
  %t13 = zext i1 false to i8
  call void @a68rt_assign(i8 %t13, i32 0)
  call void @a68rt_pop(i32 0)
  store i32 18, ptr @a68_line_no, !tbaa !16
  call void @a68rt_push_cell(i32 0, i32 1, i32 0)
  call void @a68rt_push_ref(i32 0, i32 0, i32 0)
  call void @a68rt_push_int(i64 1, i32 0)
  %t14 = load ptr, ptr %v2
  %t15 = getelementptr i8, ptr %t14, i64 0
  %t16 = load i32, ptr %t15, !tbaa !11
  %t17 = zext i32 %t16 to i64
  store i64 %t17, ptr %v5
  %t18 = load i64, ptr %v5
  %t19 = icmp eq i64 %t18, 9
  store i1 %t19, ptr %v6
  %t20 = load i1, ptr %v6
  br i1 %t20, label %b4, label %b5
b1:
  store i32 18, ptr @a68_line_no, !tbaa !16
  call void @a68rt_leave(i32 0)
  call void @a68rt_leave(i32 0)
  ret void
b2:
  store i32 18, ptr @a68_line_no, !tbaa !16
  call void @a68rt_push_cell(i32 0, i32 0, i32 0)
  call void @a68rt_monop(i32 13, i32 16, i32 0)
  %t21 = call i64 @a68rt_pop_int(i32 0)
  store i64 %t21, ptr %v15
  %t22 = load i64, ptr %v15
  store i64 %t22, ptr %v3
  br label %b3
b3:
  store i32 18, ptr @a68_line_no, !tbaa !16
  %t23 = load i64, ptr %v3
  call void @a68rt_push_int(i64 %t23, i32 0)
  call void @a68rt_push_cell(i32 0, i32 2, i32 0)
  call void @a68rt_call(i32 4, i32 0)
  %t24 = load i32, ptr @a68_jump_flag
  store i32 %t24, ptr %v16
  %t25 = load i32, ptr %v16
  %t26 = icmp ne i32 %t25, 0
  store i1 %t26, ptr %v17
  %t27 = load i1, ptr %v17
  br i1 %t27, label %b10, label %b12
b4:
  %t28 = load ptr, ptr %v2
  %t29 = getelementptr i8, ptr %t28, i64 8
  %t30 = load ptr, ptr %t29, !tbaa !11
  store ptr %t30, ptr %v7
  %t31 = load ptr, ptr %v7
  store ptr %t31, ptr %v4
  br label %b6
b5:
  %t32 = load i64, ptr %v5
  %t33 = icmp eq i64 %t32, 8
  store i1 %t33, ptr %v8
  %t34 = load i1, ptr %v8
  br i1 %t34, label %b7, label %b2
b6:
  %t35 = load ptr, ptr %v4
  %t36 = getelementptr i8, ptr %t35, i64 56
  %t37 = load i64, ptr %t36, !tbaa !12
  store i64 %t37, ptr %v14
  %t38 = load i64, ptr %v14
  store i64 %t38, ptr %v3
  br label %b3
b7:
  %t39 = load ptr, ptr %v2
  %t40 = getelementptr i8, ptr %t39, i64 4
  %t41 = load i32, ptr %t40, !tbaa !11
  %t42 = zext i32 %t41 to i64
  store i64 %t42, ptr %v9
  %t43 = load i64, ptr %v9
  %t44 = icmp eq i64 %t43, 4294967295
  store i1 %t44, ptr %v10
  %t45 = load i1, ptr %v10
  br i1 %t45, label %b8, label %b2
b8:
  %t46 = load ptr, ptr %v2
  %t47 = getelementptr i8, ptr %t46, i64 8
  %t48 = load ptr, ptr %t47, !tbaa !11
  store ptr %t48, ptr %v11
  %t49 = load ptr, ptr %v11
  %t50 = getelementptr i8, ptr %t49, i64 0
  %t51 = load i8, ptr %t50, !tbaa !12
  %t52 = zext i8 %t51 to i64
  store i64 %t52, ptr %v12
  %t53 = load i64, ptr %v12
  %t54 = icmp eq i64 %t53, 3
  store i1 %t54, ptr %v13
  %t55 = load i1, ptr %v13
  br i1 %t55, label %b9, label %b2
b9:
  %t56 = load ptr, ptr %v11
  store ptr %t56, ptr %v4
  br label %b6
b10:
  %t57 = load i32, ptr @a68_jump_flag
  store i32 %t57, ptr %v18
  %t58 = load i32, ptr %v18
  %t59 = sub i32 %t58, 1
  store i32 %t59, ptr %v19
  %t60 = load i32, ptr %v19
  switch i32 %t60, label %b11 [  ]
b11:
  ret void
b12:
  store i32 18, ptr @a68_line_no, !tbaa !16
  call void @a68rt_pop(i32 0)
  store i64 0, ptr %v1
  %t61 = load ptr, ptr %v2
  %t62 = getelementptr i8, ptr %t61, i64 0
  %t63 = load i32, ptr %t62, !tbaa !11
  %t64 = zext i32 %t63 to i64
  store i64 %t64, ptr %v23
  %t65 = load i64, ptr %v23
  %t66 = icmp eq i64 %t65, 9
  store i1 %t66, ptr %v24
  %t67 = load i1, ptr %v24
  br i1 %t67, label %b15, label %b16
b13:
  store i32 21, ptr @a68_line_no, !tbaa !16
  call void @a68rt_push_cell(i32 0, i32 0, i32 0)
  call void @a68rt_monop(i32 13, i32 16, i32 0)
  %t68 = call i64 @a68rt_pop_int(i32 0)
  store i64 %t68, ptr %v33
  %t69 = load i64, ptr %v33
  store i64 %t69, ptr %v21
  br label %b14
b14:
  store i64 1, ptr %v34
  br label %b21
b15:
  %t70 = load ptr, ptr %v2
  %t71 = getelementptr i8, ptr %t70, i64 8
  %t72 = load ptr, ptr %t71, !tbaa !11
  store ptr %t72, ptr %v25
  %t73 = load ptr, ptr %v25
  store ptr %t73, ptr %v22
  br label %b17
b16:
  %t74 = load i64, ptr %v23
  %t75 = icmp eq i64 %t74, 8
  store i1 %t75, ptr %v26
  %t76 = load i1, ptr %v26
  br i1 %t76, label %b18, label %b13
b17:
  %t77 = load ptr, ptr %v22
  %t78 = getelementptr i8, ptr %t77, i64 56
  %t79 = load i64, ptr %t78, !tbaa !12
  store i64 %t79, ptr %v32
  %t80 = load i64, ptr %v32
  store i64 %t80, ptr %v21
  br label %b14
b18:
  %t81 = load ptr, ptr %v2
  %t82 = getelementptr i8, ptr %t81, i64 4
  %t83 = load i32, ptr %t82, !tbaa !11
  %t84 = zext i32 %t83 to i64
  store i64 %t84, ptr %v27
  %t85 = load i64, ptr %v27
  %t86 = icmp eq i64 %t85, 4294967295
  store i1 %t86, ptr %v28
  %t87 = load i1, ptr %v28
  br i1 %t87, label %b19, label %b13
b19:
  %t88 = load ptr, ptr %v2
  %t89 = getelementptr i8, ptr %t88, i64 8
  %t90 = load ptr, ptr %t89, !tbaa !11
  store ptr %t90, ptr %v29
  %t91 = load ptr, ptr %v29
  %t92 = getelementptr i8, ptr %t91, i64 0
  %t93 = load i8, ptr %t92, !tbaa !12
  %t94 = zext i8 %t93 to i64
  store i64 %t94, ptr %v30
  %t95 = load i64, ptr %v30
  %t96 = icmp eq i64 %t95, 3
  store i1 %t96, ptr %v31
  %t97 = load i1, ptr %v31
  br i1 %t97, label %b20, label %b13
b20:
  %t98 = load ptr, ptr %v29
  store ptr %t98, ptr %v22
  br label %b17
b21:
  %t99 = load i64, ptr %v34
  %t100 = load i64, ptr %v21
  %t101 = icmp sgt i64 %t99, %t100
  store i1 %t101, ptr %v36
  %t102 = load i1, ptr %v36
  %t103 = and i1 true, %t102
  store i1 %t103, ptr %v37
  %t104 = load i64, ptr %v34
  %t105 = load i64, ptr %v21
  %t106 = icmp slt i64 %t104, %t105
  store i1 %t106, ptr %v39
  %t107 = load i1, ptr %v39
  %t108 = and i1 false, %t107
  store i1 %t108, ptr %v40
  %t109 = load i1, ptr %v37
  %t110 = load i1, ptr %v40
  %t111 = or i1 %t109, %t110
  store i1 %t111, ptr %v41
  %t112 = load i1, ptr %v41
  br i1 %t112, label %b23, label %b22
b22:
  store i32 21, ptr @a68_line_no, !tbaa !16
  %t113 = call ptr @a68rt_enter(i32 1, i32 0)
  %t114 = load i64, ptr %v34
  call void @a68rt_set_int(i32 0, i32 0, i64 %t114, i32 0)
  store i32 22, ptr @a68_line_no, !tbaa !16
  call void @a68rt_push_builtin(i32 17, i32 0)
  call void @a68rt_push_format(i32 28, i32 0)
  call void @a68rt_unite(i32 29, i32 0)
  %t115 = call i64 @a68rt_cell_int(i32 0, i32 0, i32 0)
  store i64 %t115, ptr %v43
  %t116 = load i64, ptr %v43
  call void @a68rt_push_int(i64 %t116, i32 0)
  call void @a68rt_unite(i32 30, i32 0)
  call void @a68rt_push_ref(i32 1, i32 0, i32 0)
  %t117 = call i64 @a68rt_cell_int(i32 0, i32 0, i32 0)
  store i64 %t117, ptr %v44
  %t118 = load i64, ptr %v44
  call void @a68rt_push_int(i64 %t118, i32 0)
  %t119 = zext i1 true to i8
  call void @a68rt_slice(i32 1, i64 0, i8 %t119, i32 0)
  %t120 = zext i1 true to i8
  call void @a68rt_select(i32 0, i8 %t120, i32 0)
  call void @a68rt_deref(i32 0)
  call void @a68rt_unite(i32 3, i32 0)
  %t121 = call i64 @a68rt_cell_int(i32 0, i32 0, i32 0)
  store i64 %t121, ptr %v45
  %t122 = load ptr, ptr %v2
  %t123 = getelementptr i8, ptr %t122, i64 0
  %t124 = load i32, ptr %t123, !tbaa !11
  %t125 = zext i32 %t124 to i64
  store i64 %t125, ptr %v48
  %t126 = load i64, ptr %v48
  %t127 = icmp eq i64 %t126, 9
  store i1 %t127, ptr %v49
  %t128 = load i1, ptr %v49
  br i1 %t128, label %b27, label %b28
b23:
  store i32 26, ptr @a68_line_no, !tbaa !16
  call void @a68rt_push_builtin(i32 17, i32 0)
  call void @a68rt_push_format(i32 40, i32 0)
  call void @a68rt_unite(i32 29, i32 0)
  %t129 = load i64, ptr %v1
  %t130 = sitofp i64 %t129 to double
  store double %t130, ptr %v135
  %t131 = load ptr, ptr %v2
  %t132 = getelementptr i8, ptr %t131, i64 0
  %t133 = load i32, ptr %t132, !tbaa !11
  %t134 = zext i32 %t133 to i64
  store i64 %t134, ptr %v138
  %t135 = load i64, ptr %v138
  %t136 = icmp eq i64 %t135, 9
  store i1 %t136, ptr %v139
  %t137 = load i1, ptr %v139
  br i1 %t137, label %b61, label %b62
b24:
  %t138 = load i64, ptr %v34
  %t139 = add i64 %t138, 1
  %t140 = icmp sgt i64 %t139, 2147483647
  %t141 = icmp slt i64 %t139, -2147483647
  %t142 = or i1 %t140, %t141
  br i1 %t142, label %trap143, label %cont143
trap143:
  store i32 26, ptr @a68_line_no, !tbaa !16
  call void @a68rt_arith_error(i32 0, i32 0)
  unreachable
cont143:
  store i64 %t139, ptr %v134
  %t144 = load i64, ptr %v134
  store i64 %t144, ptr %v34
  br label %b21
b25:
  store i32 26, ptr @a68_line_no, !tbaa !16
  %t145 = load i64, ptr %v45
  %t146 = call i64 @a68rt_sel_int(i32 1, i32 0, i32 257, i64 %t145, i64 0, i32 1, i32 0)
  store i64 %t146, ptr %v86
  %t147 = load i64, ptr %v86
  store i64 %t147, ptr %v46
  br label %b26
b26:
  store i32 26, ptr @a68_line_no, !tbaa !16
  %t148 = load i64, ptr %v46
  call void @a68rt_push_int(i64 %t148, i32 0)
  call void @a68rt_unite(i32 30, i32 0)
  %t149 = zext i1 false to i8
  call void @a68rt_collateral(i32 4, i8 %t149, i32 1, i32 0)
  call void @a68rt_call(i32 1, i32 0)
  %t150 = load i32, ptr @a68_jump_flag
  store i32 %t150, ptr %v87
  %t151 = load i32, ptr %v87
  %t152 = icmp ne i32 %t151, 0
  store i1 %t152, ptr %v88
  %t153 = load i1, ptr %v88
  br i1 %t153, label %b10, label %b41
b27:
  %t154 = load ptr, ptr %v2
  %t155 = getelementptr i8, ptr %t154, i64 8
  %t156 = load ptr, ptr %t155, !tbaa !11
  store ptr %t156, ptr %v50
  %t157 = load ptr, ptr %v50
  store ptr %t157, ptr %v47
  br label %b29
b28:
  %t158 = load i64, ptr %v48
  %t159 = icmp eq i64 %t158, 8
  store i1 %t159, ptr %v51
  %t160 = load i1, ptr %v51
  br i1 %t160, label %b30, label %b25
b29:
  %t161 = load ptr, ptr %v47
  %t162 = getelementptr i8, ptr %t161, i64 40
  %t163 = load i32, ptr %t162, !tbaa !12
  %t164 = zext i32 %t163 to i64
  store i64 %t164, ptr %v57
  %t165 = load i64, ptr %v57
  %t166 = icmp eq i64 %t165, 0
  store i1 %t166, ptr %v58
  %t167 = load i1, ptr %v58
  br i1 %t167, label %b33, label %b25
b30:
  %t168 = load ptr, ptr %v2
  %t169 = getelementptr i8, ptr %t168, i64 4
  %t170 = load i32, ptr %t169, !tbaa !11
  %t171 = zext i32 %t170 to i64
  store i64 %t171, ptr %v52
  %t172 = load i64, ptr %v52
  %t173 = icmp eq i64 %t172, 4294967295
  store i1 %t173, ptr %v53
  %t174 = load i1, ptr %v53
  br i1 %t174, label %b31, label %b25
b31:
  %t175 = load ptr, ptr %v2
  %t176 = getelementptr i8, ptr %t175, i64 8
  %t177 = load ptr, ptr %t176, !tbaa !11
  store ptr %t177, ptr %v54
  %t178 = load ptr, ptr %v54
  %t179 = getelementptr i8, ptr %t178, i64 0
  %t180 = load i8, ptr %t179, !tbaa !12
  %t181 = zext i8 %t180 to i64
  store i64 %t181, ptr %v55
  %t182 = load i64, ptr %v55
  %t183 = icmp eq i64 %t182, 3
  store i1 %t183, ptr %v56
  %t184 = load i1, ptr %v56
  br i1 %t184, label %b32, label %b25
b32:
  %t185 = load ptr, ptr %v54
  store ptr %t185, ptr %v47
  br label %b29
b33:
  %t186 = load ptr, ptr %v47
  %t187 = getelementptr i8, ptr %t186, i64 32
  %t188 = load i64, ptr %t187, !tbaa !12
  store i64 %t188, ptr %v59
  %t189 = load ptr, ptr %v47
  %t190 = getelementptr i8, ptr %t189, i64 48
  %t191 = load i64, ptr %t190, !tbaa !12
  store i64 %t191, ptr %v60
  %t192 = load ptr, ptr %v47
  %t193 = getelementptr i8, ptr %t192, i64 56
  %t194 = load i64, ptr %t193, !tbaa !12
  store i64 %t194, ptr %v61
  %t195 = load ptr, ptr %v47
  %t196 = getelementptr i8, ptr %t195, i64 64
  %t197 = load i64, ptr %t196, !tbaa !12
  store i64 %t197, ptr %v62
  %t198 = load i64, ptr %v45
  %t199 = load i64, ptr %v60
  %t200 = icmp sge i64 %t198, %t199
  store i1 %t200, ptr %v63
  %t201 = load i64, ptr %v45
  %t202 = load i64, ptr %v61
  %t203 = icmp sle i64 %t201, %t202
  store i1 %t203, ptr %v64
  %t204 = load i1, ptr %v63
  %t205 = load i1, ptr %v64
  %t206 = and i1 %t204, %t205
  store i1 %t206, ptr %v65
  %t207 = load i1, ptr %v65
  br i1 %t207, label %b35, label %b34
b34:
  store i32 26, ptr @a68_line_no, !tbaa !16
  %t208 = load i64, ptr %v45
  %t209 = load i64, ptr %v60
  %t210 = load i64, ptr %v61
  call void @a68rt_index_error(i64 %t208, i64 %t209, i64 %t210, i32 0)
  unreachable
b35:
  %t211 = load i64, ptr %v45
  %t212 = load i64, ptr %v60
  %t213 = sub i64 %t211, %t212
  store i64 %t213, ptr %v66
  %t214 = load i64, ptr %v66
  %t215 = load i64, ptr %v62
  %t216 = mul i64 %t214, %t215
  store i64 %t216, ptr %v67
  %t217 = load i64, ptr %v59
  %t218 = load i64, ptr %v67
  %t219 = add i64 %t217, %t218
  store i64 %t219, ptr %v68
  %t220 = load ptr, ptr %v47
  %t221 = getelementptr i8, ptr %t220, i64 24
  %t222 = load ptr, ptr %t221, !tbaa !12
  store ptr %t222, ptr %v69
  %t223 = load ptr, ptr %v69
  %t224 = getelementptr i8, ptr %t223, i64 0
  %t225 = load i8, ptr %t224, !tbaa !12
  %t226 = zext i8 %t225 to i64
  store i64 %t226, ptr %v70
  %t227 = load ptr, ptr %v69
  store ptr %t227, ptr %v71
  %t228 = load i64, ptr %v70
  %t229 = icmp eq i64 %t228, 3
  store i1 %t229, ptr %v72
  %t230 = load i1, ptr %v72
  br i1 %t230, label %b36, label %b37
b36:
  %t231 = load ptr, ptr %v69
  %t232 = getelementptr i8, ptr %t231, i64 24
  %t233 = load ptr, ptr %t232, !tbaa !12
  store ptr %t233, ptr %v73
  %t234 = load ptr, ptr %v73
  store ptr %t234, ptr %v71
  br label %b37
b37:
  %t235 = load ptr, ptr %v71
  %t236 = getelementptr i8, ptr %t235, i64 0
  %t237 = load i8, ptr %t236, !tbaa !12
  %t238 = zext i8 %t237 to i64
  store i64 %t238, ptr %v74
  %t239 = load i64, ptr %v74
  %t240 = icmp eq i64 %t239, 1
  store i1 %t240, ptr %v75
  %t241 = load i1, ptr %v75
  br i1 %t241, label %b38, label %b25
b38:
  %t242 = load i64, ptr %v68
  %t243 = mul i64 %t242, 16
  store i64 %t243, ptr %v76
  %t244 = load i64, ptr %v76
  %t245 = add i64 %t244, 24
  store i64 %t245, ptr %v77
  %t246 = load ptr, ptr %v71
  %t247 = load i64, ptr %v77
  %t248 = getelementptr i8, ptr %t246, i64 %t247
  %t249 = load i32, ptr %t248, !tbaa !14
  %t250 = zext i32 %t249 to i64
  store i64 %t250, ptr %v78
  %t251 = load i64, ptr %v78
  %t252 = icmp eq i64 %t251, 10
  store i1 %t252, ptr %v79
  %t253 = load i1, ptr %v79
  br i1 %t253, label %b39, label %b25
b39:
  %t254 = load i64, ptr %v77
  %t255 = add i64 %t254, 8
  store i64 %t255, ptr %v80
  %t256 = load ptr, ptr %v71
  %t257 = load i64, ptr %v80
  %t258 = getelementptr i8, ptr %t256, i64 %t257
  %t259 = load ptr, ptr %t258, !tbaa !14
  store ptr %t259, ptr %v81
  %t260 = load ptr, ptr %v81
  %t261 = getelementptr i8, ptr %t260, i64 40
  %t262 = load i32, ptr %t261, !tbaa !14
  %t263 = zext i32 %t262 to i64
  store i64 %t263, ptr %v82
  %t264 = load i64, ptr %v82
  %t265 = icmp eq i64 %t264, 1
  store i1 %t265, ptr %v83
  %t266 = load i1, ptr %v83
  br i1 %t266, label %b40, label %b25
b40:
  %t267 = load ptr, ptr %v81
  %t268 = getelementptr i8, ptr %t267, i64 48
  %t269 = load i64, ptr %t268, !tbaa !14
  store i64 %t269, ptr %v85
  %t270 = load i64, ptr %v85
  store i64 %t270, ptr %v46
  br label %b26
b41:
  store i32 26, ptr @a68_line_no, !tbaa !16
  call void @a68rt_pop(i32 0)
  store i32 23, ptr @a68_line_no, !tbaa !16
  %t271 = call i64 @a68rt_cell_int(i32 0, i32 0, i32 0)
  store i64 %t271, ptr %v89
  %t272 = load ptr, ptr %v2
  %t273 = getelementptr i8, ptr %t272, i64 0
  %t274 = load i32, ptr %t273, !tbaa !11
  %t275 = zext i32 %t274 to i64
  store i64 %t275, ptr %v92
  %t276 = load i64, ptr %v92
  %t277 = icmp eq i64 %t276, 9
  store i1 %t277, ptr %v93
  %t278 = load i1, ptr %v93
  br i1 %t278, label %b44, label %b45
b42:
  store i32 23, ptr @a68_line_no, !tbaa !16
  %t279 = load i64, ptr %v89
  %t280 = call i64 @a68rt_sel_int(i32 1, i32 0, i32 257, i64 %t279, i64 0, i32 1, i32 0)
  store i64 %t280, ptr %v130
  %t281 = load i64, ptr %v130
  store i64 %t281, ptr %v90
  br label %b43
b43:
  %t282 = load i64, ptr %v1
  %t283 = load i64, ptr %v90
  %t284 = add i64 %t282, %t283
  %t285 = icmp sgt i64 %t284, 2147483647
  %t286 = icmp slt i64 %t284, -2147483647
  %t287 = or i1 %t285, %t286
  br i1 %t287, label %trap288, label %cont288
trap288:
  store i32 23, ptr @a68_line_no, !tbaa !16
  call void @a68rt_arith_error(i32 0, i32 0)
  unreachable
cont288:
  store i64 %t284, ptr %v131
  %t289 = load i64, ptr %v131
  store i64 %t289, ptr %v1
  store i32 24, ptr @a68_line_no, !tbaa !16
  call void @a68rt_push_builtin(i32 31, i32 0)
  call void @a68rt_push_builtin(i32 32, i32 0)
  call void @a68rt_unite(i32 35, i32 0)
  call void @a68rt_row_of(i32 0)
  call void @a68rt_call(i32 1, i32 0)
  %t290 = load i32, ptr @a68_jump_flag
  store i32 %t290, ptr %v132
  %t291 = load i32, ptr %v132
  %t292 = icmp ne i32 %t291, 0
  store i1 %t292, ptr %v133
  %t293 = load i1, ptr %v133
  br i1 %t293, label %b10, label %b58
b44:
  %t294 = load ptr, ptr %v2
  %t295 = getelementptr i8, ptr %t294, i64 8
  %t296 = load ptr, ptr %t295, !tbaa !11
  store ptr %t296, ptr %v94
  %t297 = load ptr, ptr %v94
  store ptr %t297, ptr %v91
  br label %b46
b45:
  %t298 = load i64, ptr %v92
  %t299 = icmp eq i64 %t298, 8
  store i1 %t299, ptr %v95
  %t300 = load i1, ptr %v95
  br i1 %t300, label %b47, label %b42
b46:
  %t301 = load ptr, ptr %v91
  %t302 = getelementptr i8, ptr %t301, i64 40
  %t303 = load i32, ptr %t302, !tbaa !12
  %t304 = zext i32 %t303 to i64
  store i64 %t304, ptr %v101
  %t305 = load i64, ptr %v101
  %t306 = icmp eq i64 %t305, 0
  store i1 %t306, ptr %v102
  %t307 = load i1, ptr %v102
  br i1 %t307, label %b50, label %b42
b47:
  %t308 = load ptr, ptr %v2
  %t309 = getelementptr i8, ptr %t308, i64 4
  %t310 = load i32, ptr %t309, !tbaa !11
  %t311 = zext i32 %t310 to i64
  store i64 %t311, ptr %v96
  %t312 = load i64, ptr %v96
  %t313 = icmp eq i64 %t312, 4294967295
  store i1 %t313, ptr %v97
  %t314 = load i1, ptr %v97
  br i1 %t314, label %b48, label %b42
b48:
  %t315 = load ptr, ptr %v2
  %t316 = getelementptr i8, ptr %t315, i64 8
  %t317 = load ptr, ptr %t316, !tbaa !11
  store ptr %t317, ptr %v98
  %t318 = load ptr, ptr %v98
  %t319 = getelementptr i8, ptr %t318, i64 0
  %t320 = load i8, ptr %t319, !tbaa !12
  %t321 = zext i8 %t320 to i64
  store i64 %t321, ptr %v99
  %t322 = load i64, ptr %v99
  %t323 = icmp eq i64 %t322, 3
  store i1 %t323, ptr %v100
  %t324 = load i1, ptr %v100
  br i1 %t324, label %b49, label %b42
b49:
  %t325 = load ptr, ptr %v98
  store ptr %t325, ptr %v91
  br label %b46
b50:
  %t326 = load ptr, ptr %v91
  %t327 = getelementptr i8, ptr %t326, i64 32
  %t328 = load i64, ptr %t327, !tbaa !12
  store i64 %t328, ptr %v103
  %t329 = load ptr, ptr %v91
  %t330 = getelementptr i8, ptr %t329, i64 48
  %t331 = load i64, ptr %t330, !tbaa !12
  store i64 %t331, ptr %v104
  %t332 = load ptr, ptr %v91
  %t333 = getelementptr i8, ptr %t332, i64 56
  %t334 = load i64, ptr %t333, !tbaa !12
  store i64 %t334, ptr %v105
  %t335 = load ptr, ptr %v91
  %t336 = getelementptr i8, ptr %t335, i64 64
  %t337 = load i64, ptr %t336, !tbaa !12
  store i64 %t337, ptr %v106
  %t338 = load i64, ptr %v89
  %t339 = load i64, ptr %v104
  %t340 = icmp sge i64 %t338, %t339
  store i1 %t340, ptr %v107
  %t341 = load i64, ptr %v89
  %t342 = load i64, ptr %v105
  %t343 = icmp sle i64 %t341, %t342
  store i1 %t343, ptr %v108
  %t344 = load i1, ptr %v107
  %t345 = load i1, ptr %v108
  %t346 = and i1 %t344, %t345
  store i1 %t346, ptr %v109
  %t347 = load i1, ptr %v109
  br i1 %t347, label %b52, label %b51
b51:
  store i32 24, ptr @a68_line_no, !tbaa !16
  %t348 = load i64, ptr %v89
  %t349 = load i64, ptr %v104
  %t350 = load i64, ptr %v105
  call void @a68rt_index_error(i64 %t348, i64 %t349, i64 %t350, i32 0)
  unreachable
b52:
  %t351 = load i64, ptr %v89
  %t352 = load i64, ptr %v104
  %t353 = sub i64 %t351, %t352
  store i64 %t353, ptr %v110
  %t354 = load i64, ptr %v110
  %t355 = load i64, ptr %v106
  %t356 = mul i64 %t354, %t355
  store i64 %t356, ptr %v111
  %t357 = load i64, ptr %v103
  %t358 = load i64, ptr %v111
  %t359 = add i64 %t357, %t358
  store i64 %t359, ptr %v112
  %t360 = load ptr, ptr %v91
  %t361 = getelementptr i8, ptr %t360, i64 24
  %t362 = load ptr, ptr %t361, !tbaa !12
  store ptr %t362, ptr %v113
  %t363 = load ptr, ptr %v113
  %t364 = getelementptr i8, ptr %t363, i64 0
  %t365 = load i8, ptr %t364, !tbaa !12
  %t366 = zext i8 %t365 to i64
  store i64 %t366, ptr %v114
  %t367 = load ptr, ptr %v113
  store ptr %t367, ptr %v115
  %t368 = load i64, ptr %v114
  %t369 = icmp eq i64 %t368, 3
  store i1 %t369, ptr %v116
  %t370 = load i1, ptr %v116
  br i1 %t370, label %b53, label %b54
b53:
  %t371 = load ptr, ptr %v113
  %t372 = getelementptr i8, ptr %t371, i64 24
  %t373 = load ptr, ptr %t372, !tbaa !12
  store ptr %t373, ptr %v117
  %t374 = load ptr, ptr %v117
  store ptr %t374, ptr %v115
  br label %b54
b54:
  %t375 = load ptr, ptr %v115
  %t376 = getelementptr i8, ptr %t375, i64 0
  %t377 = load i8, ptr %t376, !tbaa !12
  %t378 = zext i8 %t377 to i64
  store i64 %t378, ptr %v118
  %t379 = load i64, ptr %v118
  %t380 = icmp eq i64 %t379, 1
  store i1 %t380, ptr %v119
  %t381 = load i1, ptr %v119
  br i1 %t381, label %b55, label %b42
b55:
  %t382 = load i64, ptr %v112
  %t383 = mul i64 %t382, 16
  store i64 %t383, ptr %v120
  %t384 = load i64, ptr %v120
  %t385 = add i64 %t384, 24
  store i64 %t385, ptr %v121
  %t386 = load ptr, ptr %v115
  %t387 = load i64, ptr %v121
  %t388 = getelementptr i8, ptr %t386, i64 %t387
  %t389 = load i32, ptr %t388, !tbaa !14
  %t390 = zext i32 %t389 to i64
  store i64 %t390, ptr %v122
  %t391 = load i64, ptr %v122
  %t392 = icmp eq i64 %t391, 10
  store i1 %t392, ptr %v123
  %t393 = load i1, ptr %v123
  br i1 %t393, label %b56, label %b42
b56:
  %t394 = load i64, ptr %v121
  %t395 = add i64 %t394, 8
  store i64 %t395, ptr %v124
  %t396 = load ptr, ptr %v115
  %t397 = load i64, ptr %v124
  %t398 = getelementptr i8, ptr %t396, i64 %t397
  %t399 = load ptr, ptr %t398, !tbaa !14
  store ptr %t399, ptr %v125
  %t400 = load ptr, ptr %v125
  %t401 = getelementptr i8, ptr %t400, i64 40
  %t402 = load i32, ptr %t401, !tbaa !14
  %t403 = zext i32 %t402 to i64
  store i64 %t403, ptr %v126
  %t404 = load i64, ptr %v126
  %t405 = icmp eq i64 %t404, 1
  store i1 %t405, ptr %v127
  %t406 = load i1, ptr %v127
  br i1 %t406, label %b57, label %b42
b57:
  %t407 = load ptr, ptr %v125
  %t408 = getelementptr i8, ptr %t407, i64 48
  %t409 = load i64, ptr %t408, !tbaa !14
  store i64 %t409, ptr %v129
  %t410 = load i64, ptr %v129
  store i64 %t410, ptr %v90
  br label %b43
b58:
  store i32 24, ptr @a68_line_no, !tbaa !16
  call void @a68rt_pop(i32 0)
  call void @a68rt_leave(i32 0)
  br label %b24
b59:
  store i32 24, ptr @a68_line_no, !tbaa !16
  call void @a68rt_push_cell(i32 0, i32 0, i32 0)
  call void @a68rt_monop(i32 13, i32 16, i32 0)
  %t411 = call i64 @a68rt_pop_int(i32 0)
  store i64 %t411, ptr %v148
  %t412 = load i64, ptr %v148
  store i64 %t412, ptr %v136
  br label %b60
b60:
  %t413 = load i64, ptr %v136
  %t414 = sitofp i64 %t413 to double
  store double %t414, ptr %v149
  %t415 = load double, ptr %v135
  %t416 = load double, ptr %v149
  %t418 = fcmp oeq double %t416, 0.0
  br i1 %t418, label %trap419, label %cont419
trap419:
  store i32 24, ptr @a68_line_no, !tbaa !16
  call void @a68rt_arith_error(i32 3, i32 0)
  unreachable
cont419:
  %t417 = fdiv double %t415, %t416
  store double %t417, ptr %v150
  store i32 24, ptr @a68_line_no, !tbaa !16
  %t420 = load double, ptr %v150
  call void @a68rt_push_real(double %t420, i32 0)
  call void @a68rt_unite(i32 41, i32 0)
  %t421 = zext i1 false to i8
  call void @a68rt_collateral(i32 2, i8 %t421, i32 1, i32 0)
  call void @a68rt_call(i32 1, i32 0)
  %t422 = load i32, ptr @a68_jump_flag
  store i32 %t422, ptr %v151
  %t423 = load i32, ptr %v151
  %t424 = icmp ne i32 %t423, 0
  store i1 %t424, ptr %v152
  %t425 = load i1, ptr %v152
  br i1 %t425, label %b10, label %b67
b61:
  %t426 = load ptr, ptr %v2
  %t427 = getelementptr i8, ptr %t426, i64 8
  %t428 = load ptr, ptr %t427, !tbaa !11
  store ptr %t428, ptr %v140
  %t429 = load ptr, ptr %v140
  store ptr %t429, ptr %v137
  br label %b63
b62:
  %t430 = load i64, ptr %v138
  %t431 = icmp eq i64 %t430, 8
  store i1 %t431, ptr %v141
  %t432 = load i1, ptr %v141
  br i1 %t432, label %b64, label %b59
b63:
  %t433 = load ptr, ptr %v137
  %t434 = getelementptr i8, ptr %t433, i64 56
  %t435 = load i64, ptr %t434, !tbaa !12
  store i64 %t435, ptr %v147
  %t436 = load i64, ptr %v147
  store i64 %t436, ptr %v136
  br label %b60
b64:
  %t437 = load ptr, ptr %v2
  %t438 = getelementptr i8, ptr %t437, i64 4
  %t439 = load i32, ptr %t438, !tbaa !11
  %t440 = zext i32 %t439 to i64
  store i64 %t440, ptr %v142
  %t441 = load i64, ptr %v142
  %t442 = icmp eq i64 %t441, 4294967295
  store i1 %t442, ptr %v143
  %t443 = load i1, ptr %v143
  br i1 %t443, label %b65, label %b59
b65:
  %t444 = load ptr, ptr %v2
  %t445 = getelementptr i8, ptr %t444, i64 8
  %t446 = load ptr, ptr %t445, !tbaa !11
  store ptr %t446, ptr %v144
  %t447 = load ptr, ptr %v144
  %t448 = getelementptr i8, ptr %t447, i64 0
  %t449 = load i8, ptr %t448, !tbaa !12
  %t450 = zext i8 %t449 to i64
  store i64 %t450, ptr %v145
  %t451 = load i64, ptr %v145
  %t452 = icmp eq i64 %t451, 3
  store i1 %t452, ptr %v146
  %t453 = load i1, ptr %v146
  br i1 %t453, label %b66, label %b59
b66:
  %t454 = load ptr, ptr %v144
  store ptr %t454, ptr %v137
  br label %b63
b67:
  br label %b1
}

define void @a68_fn1() {
entry:
  %v0 = alloca ptr
  %v1 = alloca i64
  %v2 = alloca i64
  %v3 = alloca i1
  %v4 = alloca i64
  %v5 = alloca i64
  %v6 = alloca ptr
  %v7 = alloca i64
  %v8 = alloca i64
  %v9 = alloca i64
  %v10 = alloca i64
  %v11 = alloca i64
  %v12 = alloca i64
  %v13 = alloca i64
  %v14 = alloca i64
  %v15 = alloca i64
  %v16 = alloca i1
  %v17 = alloca i1
  %v18 = alloca i64
  %v19 = alloca i1
  %v20 = alloca i32
  %v21 = alloca i1
  %v22 = alloca i32
  %v23 = alloca i32
  %v24 = alloca i1
  %v25 = alloca i64
  %v26 = alloca i64
  %v27 = alloca i64
  %v28 = alloca i1
  %v29 = alloca i32
  %v30 = alloca i1
  %v31 = alloca i1
  %v32 = alloca i64
  %v33 = alloca i64
  %v34 = alloca i1
  %v35 = alloca ptr
  %v36 = alloca i64
  %v37 = alloca i64
  %v38 = alloca i64
  %v39 = alloca i64
  %v40 = alloca i32
  %v41 = alloca i1
  %v42 = alloca i64
  %v43 = alloca i32
  %v44 = alloca i1
  br label %b0
b0:
  %t0 = call ptr @a68rt_enter_args(i32 4, i32 4, i32 0)
  store i32 6, ptr @a68_line_no, !tbaa !16
  %t1 = call i64 @a68rt_cell_int(i32 0, i32 1, i32 0)
  store i64 %t1, ptr %v1
  %t2 = call i64 @a68rt_cell_int(i32 0, i32 2, i32 0)
  store i64 %t2, ptr %v2
  %t3 = load i64, ptr %v1
  %t4 = load i64, ptr %v2
  %t5 = icmp slt i64 %t3, %t4
  store i1 %t5, ptr %v3
  %t6 = load i1, ptr %v3
  br i1 %t6, label %b1, label %b2
b1:
  store i32 6, ptr @a68_line_no, !tbaa !16
  %t7 = call ptr @a68rt_enter(i32 3, i32 0)
  store i32 7, ptr @a68_line_no, !tbaa !16
  call void @a68rt_push_cell(i32 1, i32 0, i32 0)
  %t8 = call i64 @a68rt_cell_int(i32 1, i32 1, i32 0)
  store i64 %t8, ptr %v7
  %t9 = call i64 @a68rt_cell_int(i32 1, i32 2, i32 0)
  store i64 %t9, ptr %v8
  %t10 = load i64, ptr %v7
  %t11 = load i64, ptr %v8
  %t12 = add i64 %t10, %t11
  %t13 = icmp sgt i64 %t12, 2147483647
  %t14 = icmp slt i64 %t12, -2147483647
  %t15 = or i1 %t13, %t14
  br i1 %t15, label %trap16, label %cont16
trap16:
  store i32 7, ptr @a68_line_no, !tbaa !16
  call void @a68rt_arith_error(i32 0, i32 0)
  unreachable
cont16:
  store i64 %t12, ptr %v9
  %t17 = load i64, ptr %v9
  %t19 = icmp eq i64 2, 0
  br i1 %t19, label %trap20, label %cont20
trap20:
  store i32 7, ptr @a68_line_no, !tbaa !16
  call void @a68rt_arith_error(i32 1, i32 0)
  unreachable
cont20:
  %t18 = sdiv i64 %t17, 2
  store i64 %t18, ptr %v10
  %t21 = load i64, ptr %v10
  call void @a68rt_push_int(i64 %t21, i32 0)
  %t22 = zext i1 true to i8
  call void @a68rt_slice(i32 1, i64 0, i8 %t22, i32 0)
  call void @a68rt_deref(i32 0)
  call void @a68rt_store(i32 0, i32 0, i32 0)
  store i32 8, ptr @a68_line_no, !tbaa !16
  %t23 = call i64 @a68rt_cell_int(i32 1, i32 1, i32 0)
  store i64 %t23, ptr %v12
  %t24 = load i64, ptr %v12
  store i64 %t24, ptr %v4
  %t25 = call i64 @a68rt_cell_int(i32 1, i32 2, i32 0)
  store i64 %t25, ptr %v14
  %t26 = load i64, ptr %v14
  store i64 %t26, ptr %v5
  store i64 1, ptr %v15
  br label %b5
b2:
  store i32 9, ptr @a68_line_no, !tbaa !16
  call void @a68rt_push_skip(i32 0, i32 0)
  br label %b3
b3:
  store i32 9, ptr @a68_line_no, !tbaa !16
  call void @a68rt_leave(i32 0)
  ret void
b4:
  store i32 9, ptr @a68_line_no, !tbaa !16
  call void @a68rt_leave(i32 0)
  br label %b3
b5:
  br label %b6
b6:
  %t27 = load i64, ptr %v4
  %t28 = load i64, ptr %v5
  %t29 = icmp sle i64 %t27, %t28
  store i1 %t29, ptr %v17
  %t30 = load i1, ptr %v17
  br i1 %t30, label %b9, label %b10
b7:
  store i32 14, ptr @a68_line_no, !tbaa !16
  call void @a68rt_push_cell(i32 2, i32 1, i32 0)
  call void @a68rt_push_cell(i32 1, i32 0, i32 0)
  %t31 = call i64 @a68rt_cell_int(i32 1, i32 1, i32 0)
  store i64 %t31, ptr %v39
  %t32 = load i64, ptr %v39
  call void @a68rt_push_int(i64 %t32, i32 0)
  %t33 = load i64, ptr %v5
  call void @a68rt_push_int(i64 %t33, i32 0)
  call void @a68rt_push_cell(i32 1, i32 3, i32 0)
  call void @a68rt_call(i32 4, i32 0)
  %t34 = load i32, ptr @a68_jump_flag
  store i32 %t34, ptr %v40
  %t35 = load i32, ptr %v40
  %t36 = icmp ne i32 %t35, 0
  store i1 %t36, ptr %v41
  %t37 = load i1, ptr %v41
  br i1 %t37, label %b16, label %b40
b8:
  %t38 = load i64, ptr %v15
  %t39 = add i64 %t38, 1
  %t40 = icmp sgt i64 %t39, 2147483647
  %t41 = icmp slt i64 %t39, -2147483647
  %t42 = or i1 %t40, %t41
  br i1 %t42, label %trap43, label %cont43
trap43:
  store i32 14, ptr @a68_line_no, !tbaa !16
  call void @a68rt_arith_error(i32 0, i32 0)
  unreachable
cont43:
  store i64 %t39, ptr %v38
  %t44 = load i64, ptr %v38
  store i64 %t44, ptr %v15
  br label %b5
b9:
  store i64 1, ptr %v18
  br label %b12
b10:
  store i1 false, ptr %v16
  br label %b11
b11:
  %t45 = load i1, ptr %v16
  br i1 %t45, label %b38, label %b39
b12:
  br label %b13
b13:
  store i32 10, ptr @a68_line_no, !tbaa !16
  call void @a68rt_push_cell(i32 1, i32 3, i32 0)
  call void @a68rt_push_cell(i32 1, i32 0, i32 0)
  %t46 = load i64, ptr %v4
  call void @a68rt_push_int(i64 %t46, i32 0)
  %t47 = zext i1 true to i8
  call void @a68rt_slice(i32 1, i64 0, i8 %t47, i32 0)
  call void @a68rt_deref(i32 0)
  call void @a68rt_push_cell(i32 0, i32 0, i32 0)
  call void @a68rt_call(i32 2, i32 0)
  %t48 = load i32, ptr @a68_jump_flag
  store i32 %t48, ptr %v20
  %t49 = load i32, ptr %v20
  %t50 = icmp ne i32 %t49, 0
  store i1 %t50, ptr %v21
  %t51 = load i1, ptr %v21
  br i1 %t51, label %b16, label %b18
b14:
  store i64 1, ptr %v27
  br label %b24
b15:
  %t52 = load i64, ptr %v18
  %t53 = add i64 %t52, 1
  %t54 = icmp sgt i64 %t53, 2147483647
  %t55 = icmp slt i64 %t53, -2147483647
  %t56 = or i1 %t54, %t55
  br i1 %t56, label %trap57, label %cont57
trap57:
  store i32 11, ptr @a68_line_no, !tbaa !16
  call void @a68rt_arith_error(i32 0, i32 0)
  unreachable
cont57:
  store i64 %t53, ptr %v26
  %t58 = load i64, ptr %v26
  store i64 %t58, ptr %v18
  br label %b12
b16:
  %t59 = load i32, ptr @a68_jump_flag
  store i32 %t59, ptr %v22
  %t60 = load i32, ptr %v22
  %t61 = sub i32 %t60, 1
  store i32 %t61, ptr %v23
  %t62 = load i32, ptr %v23
  switch i32 %t62, label %b17 [  ]
b17:
  ret void
b18:
  store i32 11, ptr @a68_line_no, !tbaa !16
  %t63 = call i8 @a68rt_pop_bool(i32 0)
  %t64 = icmp ne i8 %t63, 0
  store i1 %t64, ptr %v24
  %t65 = load i1, ptr %v24
  br i1 %t65, label %b19, label %b20
b19:
  %t66 = load i64, ptr %v4
  %t67 = add i64 %t66, 1
  %t68 = icmp sgt i64 %t67, 2147483647
  %t69 = icmp slt i64 %t67, -2147483647
  %t70 = or i1 %t68, %t69
  br i1 %t70, label %trap71, label %cont71
trap71:
  store i32 10, ptr @a68_line_no, !tbaa !16
  call void @a68rt_arith_error(i32 0, i32 0)
  unreachable
cont71:
  store i64 %t67, ptr %v25
  %t72 = load i64, ptr %v25
  store i64 %t72, ptr %v4
  store i1 true, ptr %v19
  br label %b21
b20:
  store i1 false, ptr %v19
  br label %b21
b21:
  %t73 = load i1, ptr %v19
  br i1 %t73, label %b22, label %b23
b22:
  br label %b15
b23:
  br label %b14
b24:
  br label %b25
b25:
  store i32 11, ptr @a68_line_no, !tbaa !16
  call void @a68rt_push_cell(i32 1, i32 3, i32 0)
  call void @a68rt_push_cell(i32 0, i32 0, i32 0)
  call void @a68rt_push_cell(i32 1, i32 0, i32 0)
  %t74 = load i64, ptr %v5
  call void @a68rt_push_int(i64 %t74, i32 0)
  %t75 = zext i1 true to i8
  call void @a68rt_slice(i32 1, i64 0, i8 %t75, i32 0)
  call void @a68rt_deref(i32 0)
  call void @a68rt_call(i32 2, i32 0)
  %t76 = load i32, ptr @a68_jump_flag
  store i32 %t76, ptr %v29
  %t77 = load i32, ptr %v29
  %t78 = icmp ne i32 %t77, 0
  store i1 %t78, ptr %v30
  %t79 = load i1, ptr %v30
  br i1 %t79, label %b16, label %b28
b26:
  %t80 = load i64, ptr %v4
  %t81 = load i64, ptr %v5
  %t82 = icmp sle i64 %t80, %t81
  store i1 %t82, ptr %v34
  %t83 = load i1, ptr %v34
  br i1 %t83, label %b34, label %b35
b27:
  %t84 = load i64, ptr %v27
  %t85 = add i64 %t84, 1
  %t86 = icmp sgt i64 %t85, 2147483647
  %t87 = icmp slt i64 %t85, -2147483647
  %t88 = or i1 %t86, %t87
  br i1 %t88, label %trap89, label %cont89
trap89:
  store i32 12, ptr @a68_line_no, !tbaa !16
  call void @a68rt_arith_error(i32 0, i32 0)
  unreachable
cont89:
  store i64 %t85, ptr %v33
  %t90 = load i64, ptr %v33
  store i64 %t90, ptr %v27
  br label %b24
b28:
  store i32 12, ptr @a68_line_no, !tbaa !16
  %t91 = call i8 @a68rt_pop_bool(i32 0)
  %t92 = icmp ne i8 %t91, 0
  store i1 %t92, ptr %v31
  %t93 = load i1, ptr %v31
  br i1 %t93, label %b29, label %b30
b29:
  %t94 = load i64, ptr %v5
  %t95 = sub i64 %t94, 1
  %t96 = icmp sgt i64 %t95, 2147483647
  %t97 = icmp slt i64 %t95, -2147483647
  %t98 = or i1 %t96, %t97
  br i1 %t98, label %trap99, label %cont99
trap99:
  store i32 11, ptr @a68_line_no, !tbaa !16
  call void @a68rt_arith_error(i32 0, i32 0)
  unreachable
cont99:
  store i64 %t95, ptr %v32
  %t100 = load i64, ptr %v32
  store i64 %t100, ptr %v5
  store i1 true, ptr %v28
  br label %b31
b30:
  store i1 false, ptr %v28
  br label %b31
b31:
  %t101 = load i1, ptr %v28
  br i1 %t101, label %b32, label %b33
b32:
  br label %b27
b33:
  br label %b26
b34:
  store i32 11, ptr @a68_line_no, !tbaa !16
  %t102 = call ptr @a68rt_enter(i32 1, i32 0)
  store i32 12, ptr @a68_line_no, !tbaa !16
  call void @a68rt_push_cell(i32 2, i32 0, i32 0)
  %t103 = load i64, ptr %v4
  call void @a68rt_push_int(i64 %t103, i32 0)
  %t104 = zext i1 true to i8
  call void @a68rt_slice(i32 1, i64 0, i8 %t104, i32 0)
  call void @a68rt_deref(i32 0)
  call void @a68rt_store(i32 0, i32 0, i32 0)
  call void @a68rt_push_cell(i32 2, i32 0, i32 0)
  %t105 = load i64, ptr %v4
  call void @a68rt_push_int(i64 %t105, i32 0)
  %t106 = zext i1 true to i8
  call void @a68rt_slice(i32 1, i64 0, i8 %t106, i32 0)
  call void @a68rt_push_cell(i32 2, i32 0, i32 0)
  %t107 = load i64, ptr %v5
  call void @a68rt_push_int(i64 %t107, i32 0)
  %t108 = zext i1 true to i8
  call void @a68rt_slice(i32 1, i64 0, i8 %t108, i32 0)
  call void @a68rt_deref(i32 0)
  %t109 = zext i1 false to i8
  call void @a68rt_assign(i8 %t109, i32 0)
  call void @a68rt_pop(i32 0)
  call void @a68rt_push_cell(i32 2, i32 0, i32 0)
  %t110 = load i64, ptr %v5
  call void @a68rt_push_int(i64 %t110, i32 0)
  %t111 = zext i1 true to i8
  call void @a68rt_slice(i32 1, i64 0, i8 %t111, i32 0)
  call void @a68rt_push_cell(i32 0, i32 0, i32 0)
  %t112 = zext i1 false to i8
  call void @a68rt_assign(i8 %t112, i32 0)
  call void @a68rt_pop(i32 0)
  %t113 = load i64, ptr %v4
  %t114 = add i64 %t113, 1
  %t115 = icmp sgt i64 %t114, 2147483647
  %t116 = icmp slt i64 %t114, -2147483647
  %t117 = or i1 %t115, %t116
  br i1 %t117, label %trap118, label %cont118
trap118:
  store i32 12, ptr @a68_line_no, !tbaa !16
  call void @a68rt_arith_error(i32 0, i32 0)
  unreachable
cont118:
  store i64 %t114, ptr %v36
  %t119 = load i64, ptr %v36
  store i64 %t119, ptr %v4
  %t120 = load i64, ptr %v5
  %t121 = sub i64 %t120, 1
  %t122 = icmp sgt i64 %t121, 2147483647
  %t123 = icmp slt i64 %t121, -2147483647
  %t124 = or i1 %t122, %t123
  br i1 %t124, label %trap125, label %cont125
trap125:
  store i32 12, ptr @a68_line_no, !tbaa !16
  call void @a68rt_arith_error(i32 0, i32 0)
  unreachable
cont125:
  store i64 %t121, ptr %v37
  %t126 = load i64, ptr %v37
  store i64 %t126, ptr %v5
  br label %b37
b35:
  br label %b36
b36:
  store i1 true, ptr %v16
  br label %b11
b37:
  store i32 12, ptr @a68_line_no, !tbaa !16
  call void @a68rt_leave(i32 0)
  br label %b36
b38:
  br label %b8
b39:
  br label %b7
b40:
  store i32 12, ptr @a68_line_no, !tbaa !16
  call void @a68rt_pop(i32 0)
  store i32 14, ptr @a68_line_no, !tbaa !16
  call void @a68rt_push_cell(i32 2, i32 1, i32 0)
  call void @a68rt_push_cell(i32 1, i32 0, i32 0)
  %t127 = load i64, ptr %v4
  call void @a68rt_push_int(i64 %t127, i32 0)
  %t128 = call i64 @a68rt_cell_int(i32 1, i32 2, i32 0)
  store i64 %t128, ptr %v42
  %t129 = load i64, ptr %v42
  call void @a68rt_push_int(i64 %t129, i32 0)
  call void @a68rt_push_cell(i32 1, i32 3, i32 0)
  call void @a68rt_call(i32 4, i32 0)
  %t130 = load i32, ptr @a68_jump_flag
  store i32 %t130, ptr %v43
  %t131 = load i32, ptr %v43
  %t132 = icmp ne i32 %t131, 0
  store i1 %t132, ptr %v44
  %t133 = load i1, ptr %v44
  br i1 %t133, label %b16, label %b41
b41:
  br label %b4
}

define void @a68_fn2() {
entry:
  %v0 = alloca ptr
  %v1 = alloca i64
  %v2 = alloca i64
  %v3 = alloca i1
  %v4 = alloca i64
  %v5 = alloca i64
  %v6 = alloca i1
  %v7 = alloca i1
  %v8 = alloca i1
  %v9 = alloca i1
  br label %b0
b0:
  %t0 = call ptr @a68rt_enter_args(i32 2, i32 2, i32 0)
  call void @a68rt_push_cell(i32 0, i32 0, i32 0)
  %t1 = zext i1 false to i8
  call void @a68rt_select(i32 1, i8 %t1, i32 0)
  %t2 = call i64 @a68rt_pop_int(i32 0)
  store i64 %t2, ptr %v1
  call void @a68rt_push_cell(i32 0, i32 1, i32 0)
  %t3 = zext i1 false to i8
  call void @a68rt_select(i32 1, i8 %t3, i32 0)
  %t4 = call i64 @a68rt_pop_int(i32 0)
  store i64 %t4, ptr %v2
  %t5 = load i64, ptr %v1
  %t6 = load i64, ptr %v2
  %t7 = icmp slt i64 %t5, %t6
  store i1 %t7, ptr %v3
  store i32 17, ptr @a68_line_no, !tbaa !16
  call void @a68rt_push_cell(i32 0, i32 0, i32 0)
  %t8 = zext i1 false to i8
  call void @a68rt_select(i32 1, i8 %t8, i32 0)
  %t9 = call i64 @a68rt_pop_int(i32 0)
  store i64 %t9, ptr %v4
  call void @a68rt_push_cell(i32 0, i32 1, i32 0)
  %t10 = zext i1 false to i8
  call void @a68rt_select(i32 1, i8 %t10, i32 0)
  %t11 = call i64 @a68rt_pop_int(i32 0)
  store i64 %t11, ptr %v5
  %t12 = load i64, ptr %v4
  %t13 = load i64, ptr %v5
  %t14 = icmp eq i64 %t12, %t13
  store i1 %t14, ptr %v6
  call void @a68rt_push_cell(i32 0, i32 0, i32 0)
  %t15 = zext i1 false to i8
  call void @a68rt_select(i32 0, i8 %t15, i32 0)
  call void @a68rt_push_cell(i32 0, i32 1, i32 0)
  %t16 = zext i1 false to i8
  call void @a68rt_select(i32 0, i8 %t16, i32 0)
  call void @a68rt_dyop(i32 1, i32 3, i32 3, i32 0)
  %t17 = call i8 @a68rt_pop_bool(i32 0)
  %t18 = icmp ne i8 %t17, 0
  store i1 %t18, ptr %v7
  %t19 = load i1, ptr %v6
  %t20 = load i1, ptr %v7
  %t21 = and i1 %t19, %t20
  store i1 %t21, ptr %v8
  %t22 = load i1, ptr %v3
  %t23 = load i1, ptr %v8
  %t24 = or i1 %t22, %t23
  store i1 %t24, ptr %v9
  %t25 = load i1, ptr %v9
  %t26 = zext i1 %t25 to i8
  call void @a68rt_push_bool(i8 %t26, i32 0)
  call void @a68rt_leave(i32 0)
  ret void
}

define void @a68_dispatch_proc(i64 %fn) {
entry:
  switch i64 %fn, label %none [ i64 0, label %f0 i64 1, label %f1 i64 2, label %f2 ]
f0:
  call void @a68_fn0()
  ret void
f1:
  call void @a68_fn1()
  ret void
f2:
  call void @a68_fn2()
  ret void
none:
  ret void
}

define void @a68_dispatch_hole(i64 %idx) {
entry:
  switch i64 %idx, label %none [  ]
none:
  ret void
}

define i32 @main(i32 %argc, ptr %argv) {
entry:
  call void @a68rt_boot(ptr @A68_BLOB, i32 12, i8 0, i32 %argc, ptr %argv, ptr @A68_SRC)
  call void @a68_fn0()
  %rc = call i32 @a68rt_finish(i32 0)
  ret i32 %rc
}
!0 = !{!"a68 memory"}
!1 = !{!"a cell or a slot", !0}
!2 = !{!"a frame cell", !1}
!3 = !{!"a slot value", !1}
!4 = !{!"an object header", !0}
!5 = !{!"leaf data", !0}
!6 = !{!"the line number", !0}
!11 = !{!2, !2, i64 0}
!12 = !{!4, !4, i64 0}
!13 = !{!5, !5, i64 0}
!14 = !{!3, !3, i64 0}
!15 = !{!1, !1, i64 0}
!16 = !{!6, !6, i64 0}