; generated by a68lean compile --llvm
target triple = "arm64-apple-macosx"

@a68_line_no = external global i32
@a68_jump_flag = external global i32
@A68_BLOB = private constant [247 x i8] c"s 7072696e7466\0Af dig 0\0Af rep 4 0 1\0Ak 1 2\0Am format\0Am int 0\0As 7072696e74\0As 6e65776c696e65\0Am file\0Am ref 8\0Am void\0Am proc 10 1 9\0As 7072696d657320757020746f20\0Af lit 12\0Ac hole 0 0\0Af gen 1 14\0As 3a20\0Af lit 16\0Ac hole 0 1\0Af gen 1 18\0Af nl\0Ak 5 13 15 17 19 20\0A\00"
@A68_SRC = private constant [10 x i8] c"sieve.a68\00"
declare void @a68rt_boot(ptr, i32, i8, i32, ptr, ptr)
@a68_nf_of_fn = internal constant [2 x ptr] [ptr null, ptr null]
declare i32 @a68rt_finish(i32)
declare void @a68rt_row_of(i32)
declare void @a68rt_pop(i32)
declare void @a68rt_call(i32, i32)
declare void @a68rt_collateral(i32, i8, i32, i32)
declare void @a68rt_unite(i32, i32)
declare void @a68rt_push_format(i32, i32)
declare void @a68rt_push_builtin(i32, i32)
declare i64 @a68rt_cell_int(i32, i32, i32)
declare void @a68rt_set_int(i32, i32, i64, i32)
declare void @a68rt_undef_error(i32, i32)
declare i8 @a68rt_row_bool(i32, i32, i32, i64, i64, i32)
declare void @a68rt_index_error(i64, i64, i64, i32)
declare void @a68rt_set_row_bool(i32, i32, i32, i64, i64, i8, i32)
declare void @a68rt_arith_error(i32, i32)
declare void @a68rt_leave(i32)
declare void @a68rt_store(i32, i32, i32)
declare void @a68rt_new_row_of(i32, i8, i32, i32)
declare void @a68rt_push_int(i64, i32)
declare void @a68rt_push_undef(i32)
declare ptr @a68rt_enter(i32, i32)
declare ptr @a68rt_enter_args(i32, i32, i32)

define void @a68_fn0() {
entry:
  %v0 = alloca ptr
  %v1 = alloca i64
  %v2 = alloca i64
  %v3 = alloca i64
  %v4 = alloca ptr
  %v5 = alloca i64
  %v6 = alloca i1
  %v7 = alloca i1
  %v8 = alloca ptr
  %v9 = alloca ptr
  %v10 = alloca i64
  %v11 = alloca i64
  %v12 = alloca i64
  %v13 = alloca i64
  %v14 = alloca i64
  %v15 = alloca i64
  %v16 = alloca i1
  %v17 = alloca ptr
  %v18 = alloca i64
  %v19 = alloca i1
  %v20 = alloca ptr
  %v21 = alloca i64
  %v22 = alloca ptr
  %v23 = alloca i1
  %v24 = alloca ptr
  %v25 = alloca i64
  %v26 = alloca i1
  %v27 = alloca i64
  %v28 = alloca i1
  %v29 = alloca i64
  %v30 = alloca i64
  %v31 = alloca i1
  %v32 = alloca i64
  %v33 = alloca i1
  %v34 = alloca i1
  %v35 = alloca i1
  %v36 = alloca i1
  %v37 = alloca i1
  %v38 = alloca i1
  %v39 = alloca i1
  %v40 = alloca i1
  %v41 = alloca i1
  %v42 = alloca i1
  %v43 = alloca i64
  %v44 = alloca i64
  %v45 = alloca i64
  %v46 = alloca i64
  %v47 = alloca i64
  %v48 = alloca i64
  %v49 = alloca i64
  %v50 = alloca i64
  %v51 = alloca i64
  %v52 = alloca i1
  %v53 = alloca ptr
  %v54 = alloca i64
  %v55 = alloca i1
  %v56 = alloca ptr
  %v57 = alloca i64
  %v58 = alloca ptr
  %v59 = alloca i1
  %v60 = alloca ptr
  %v61 = alloca i64
  %v62 = alloca i1
  %v63 = alloca i64
  %v64 = alloca i1
  %v65 = alloca i64
  %v66 = alloca i64
  %v67 = alloca i1
  %v68 = alloca i64
  %v69 = alloca ptr
  %v70 = alloca i64
  %v71 = alloca i1
  %v72 = alloca ptr
  %v73 = alloca i1
  %v74 = alloca i64
  %v75 = alloca i1
  %v76 = alloca ptr
  %v77 = alloca i64
  %v78 = alloca i1
  %v79 = alloca i64
  %v80 = alloca i1
  %v81 = alloca i64
  %v82 = alloca i64
  %v83 = alloca i64
  %v84 = alloca i64
  %v85 = alloca i1
  %v86 = alloca i1
  %v87 = alloca i1
  %v88 = alloca i64
  %v89 = alloca i64
  %v90 = alloca i64
  %v91 = alloca ptr
  %v92 = alloca i64
  %v93 = alloca ptr
  %v94 = alloca i1
  %v95 = alloca ptr
  %v96 = alloca i64
  %v97 = alloca i1
  %v98 = alloca i64
  %v99 = alloca i1
  %v100 = alloca i64
  %v101 = alloca i1
  %v102 = alloca i64
  %v103 = alloca i64
  %v104 = alloca i64
  %v105 = alloca i64
  %v106 = alloca i64
  %v107 = alloca i64
  %v108 = alloca i1
  %v109 = alloca i1
  %v110 = alloca ptr
  %v111 = alloca ptr
  %v112 = alloca i64
  %v113 = alloca i64
  %v114 = alloca i64
  %v115 = alloca i64
  %v116 = alloca i64
  %v117 = alloca i64
  %v118 = alloca i1
  %v119 = alloca ptr
  %v120 = alloca i64
  %v121 = alloca i1
  %v122 = alloca ptr
  %v123 = alloca i64
  %v124 = alloca ptr
  %v125 = alloca i1
  %v126 = alloca ptr
  %v127 = alloca i64
  %v128 = alloca i1
  %v129 = alloca i64
  %v130 = alloca i1
  %v131 = alloca i64
  %v132 = alloca i64
  %v133 = alloca i1
  %v134 = alloca i64
  %v135 = alloca i1
  %v136 = alloca i1
  %v137 = alloca i1
  %v138 = alloca i1
  %v139 = alloca i1
  %v140 = alloca i1
  %v141 = alloca i1
  %v142 = alloca i1
  %v143 = alloca i1
  %v144 = alloca i1
  %v145 = alloca i1
  %v146 = alloca i64
  %v147 = alloca i64
  %v148 = alloca i64
  %v149 = alloca i64
  %v150 = alloca i64
  %v151 = alloca i64
  %v152 = alloca i64
  %v153 = alloca i1
  %v154 = alloca i64
  %v155 = alloca i64
  %v156 = alloca i64
  %v157 = alloca i1
  %v158 = alloca i1
  %v159 = alloca i64
  %v160 = alloca i1
  %v161 = alloca ptr
  %v162 = alloca i64
  %v163 = alloca i1
  %v164 = alloca ptr
  %v165 = alloca i64
  %v166 = alloca ptr
  %v167 = alloca i1
  %v168 = alloca ptr
  %v169 = alloca i64
  %v170 = alloca i1
  %v171 = alloca i64
  %v172 = alloca i1
  %v173 = alloca i64
  %v174 = alloca i64
  %v175 = alloca i1
  %v176 = alloca i64
  %v177 = alloca i64
  %v178 = alloca i64
  %v179 = alloca i64
  %v180 = alloca i1
  %v181 = alloca i1
  %v182 = alloca i1
  %v183 = alloca i1
  %v184 = alloca i1
  %v185 = alloca i64
  %v186 = alloca i64
  %v187 = alloca i64
  %v188 = alloca i64
  %v189 = alloca i64
  %v190 = alloca i64
  %v191 = alloca i64
  %v192 = alloca i64
  %v193 = alloca i64
  %v194 = alloca i1
  %v195 = alloca ptr
  %v196 = alloca i64
  %v197 = alloca i1
  %v198 = alloca ptr
  %v199 = alloca i64
  %v200 = alloca ptr
  %v201 = alloca i1
  %v202 = alloca ptr
  %v203 = alloca i64
  %v204 = alloca i1
  %v205 = alloca i64
  %v206 = alloca i1
  %v207 = alloca i64
  %v208 = alloca i64
  %v209 = alloca i1
  %v210 = alloca i64
  %v211 = alloca i64
  %v212 = alloca i64
  %v213 = alloca i64
  %v214 = alloca i64
  %v215 = alloca i64
  %v216 = alloca i1
  %v217 = alloca i1
  %v218 = alloca i1
  %v219 = alloca i1
  %v220 = alloca i1
  %v221 = alloca i1
  %v222 = alloca i1
  %v223 = alloca ptr
  %v224 = alloca i64
  %v225 = alloca i1
  %v226 = alloca ptr
  %v227 = alloca i64
  %v228 = alloca i1
  %v229 = alloca ptr
  %v230 = alloca i1
  %v231 = alloca i64
  %v232 = alloca i1
  %v233 = alloca ptr
  %v234 = alloca i64
  %v235 = alloca i1
  %v236 = alloca i64
  %v237 = alloca i1
  %v238 = alloca i64
  %v239 = alloca i64
  %v240 = alloca i64
  %v241 = alloca i64
  %v242 = alloca i1
  %v243 = alloca i1
  %v244 = alloca i1
  %v245 = alloca i64
  %v246 = alloca i64
  %v247 = alloca i64
  %v248 = alloca ptr
  %v249 = alloca i64
  %v250 = alloca ptr
  %v251 = alloca i1
  %v252 = alloca ptr
  %v253 = alloca i64
  %v254 = alloca i1
  %v255 = alloca i64
  %v256 = alloca i1
  %v257 = alloca i64
  %v258 = alloca i64
  %v259 = alloca i64
  %v260 = alloca i64
  %v261 = alloca i64
  %v262 = alloca i1
  %v263 = alloca i64
  %v264 = alloca i64
  %v265 = alloca i64
  %v266 = alloca i1
  %v267 = alloca i1
  %v268 = alloca i64
  %v269 = alloca i64
  %v270 = alloca i32
  %v271 = alloca i1
  %v272 = alloca i32
  %v273 = alloca i32
  %v274 = alloca i64
  %v275 = alloca i1
  %v276 = alloca i32
  %v277 = alloca i1
  %v278 = alloca i64
  %v279 = alloca i64
  %v280 = alloca i1
  %v281 = alloca i32
  %v282 = alloca i1
  %v283 = alloca i32
  %v284 = alloca i1
  br label %b0
b0:
  %t0 = call ptr @a68rt_enter_args(i32 0, i32 0, i32 0)
  store i32 4, ptr @a68_line_no, !tbaa !16
  %t1 = call ptr @a68rt_enter(i32 4, i32 0)
  store ptr %t1, ptr %v4
  store i32 5, ptr @a68_line_no, !tbaa !16
  call void @a68rt_push_undef(i32 0)
  call void @a68rt_push_int(i64 1, i32 0)
  call void @a68rt_push_int(i64 100, i32 0)
  %t2 = zext i1 false to i8
  call void @a68rt_new_row_of(i32 1, i8 %t2, i32 3, i32 0)
  call void @a68rt_store(i32 0, i32 1, i32 0)
  store i1 false, ptr %v6
  store i1 false, ptr %v7
  %t3 = load ptr, ptr %v4
  %t4 = getelementptr i8, ptr %t3, i64 16
  %t5 = load i32, ptr %t4, !tbaa !11
  %t6 = zext i32 %t5 to i64
  store i64 %t6, ptr %v15
  %t7 = load i64, ptr %v15
  %t8 = icmp eq i64 %t7, 9
  store i1 %t8, ptr %v16
  %t9 = load i1, ptr %v16
  br i1 %t9, label %b3, label %b2
b1:
  store i32 7, ptr @a68_line_no, !tbaa !16
  call void @a68rt_leave(i32 0)
  call void @a68rt_leave(i32 0)
  ret void
b2:
  store i64 1, ptr %v32
  br label %b9
b3:
  %t10 = load ptr, ptr %v4
  %t11 = getelementptr i8, ptr %t10, i64 24
  %t12 = load ptr, ptr %t11, !tbaa !11
  store ptr %t12, ptr %v17
  %t13 = load ptr, ptr %v17
  %t14 = getelementptr i8, ptr %t13, i64 40
  %t15 = load i32, ptr %t14, !tbaa !12
  %t16 = zext i32 %t15 to i64
  store i64 %t16, ptr %v18
  %t17 = load i64, ptr %v18
  %t18 = icmp eq i64 %t17, 0
  store i1 %t18, ptr %v19
  %t19 = load i1, ptr %v19
  br i1 %t19, label %b4, label %b2
b4:
  store i64 0, ptr %v10
  store i64 1, ptr %v12
  store i64 100, ptr %v13
  store i64 1, ptr %v14
  %t20 = load ptr, ptr %v17
  %t21 = getelementptr i8, ptr %t20, i64 24
  %t22 = load ptr, ptr %t21, !tbaa !12
  store ptr %t22, ptr %v20
  %t23 = load ptr, ptr %v20
  %t24 = getelementptr i8, ptr %t23, i64 0
  %t25 = load i8, ptr %t24, !tbaa !12
  %t26 = zext i8 %t25 to i64
  store i64 %t26, ptr %v21
  %t27 = load ptr, ptr %v20
  store ptr %t27, ptr %v22
  %t28 = load i64, ptr %v21
  %t29 = icmp eq i64 %t28, 3
  store i1 %t29, ptr %v23
  %t30 = load i1, ptr %v23
  br i1 %t30, label %b5, label %b6
b5:
  %t31 = load ptr, ptr %v20
  %t32 = getelementptr i8, ptr %t31, i64 24
  %t33 = load ptr, ptr %t32, !tbaa !12
  store ptr %t33, ptr %v24
  %t34 = load ptr, ptr %v24
  store ptr %t34, ptr %v22
  br label %b6
b6:
  %t35 = load ptr, ptr %v22
  store ptr %t35, ptr %v9
  %t36 = load ptr, ptr %v22
  %t37 = getelementptr i8, ptr %t36, i64 0
  %t38 = load i8, ptr %t37, !tbaa !12
  %t39 = zext i8 %t38 to i64
  store i64 %t39, ptr %v25
  %t40 = load i64, ptr %v25
  %t41 = icmp eq i64 %t40, 2
  store i1 %t41, ptr %v26
  %t42 = load i1, ptr %v26
  br i1 %t42, label %b7, label %b2
b7:
  %t43 = load ptr, ptr %v22
  %t44 = getelementptr i8, ptr %t43, i64 2
  %t45 = load i16, ptr %t44, !tbaa !12
  %t46 = zext i16 %t45 to i64
  store i64 %t46, ptr %v27
  %t47 = load i64, ptr %v27
  %t48 = icmp eq i64 %t47, 3
  store i1 %t48, ptr %v28
  %t49 = load i1, ptr %v28
  br i1 %t49, label %b8, label %b2
b8:
  %t50 = load ptr, ptr %v22
  %t51 = getelementptr i8, ptr %t50, i64 4
  %t52 = load i32, ptr %t51, !tbaa !12
  %t53 = zext i32 %t52 to i64
  store i64 %t53, ptr %v29
  %t54 = load i64, ptr %v29
  store i64 %t54, ptr %v11
  store i1 true, ptr %v6
  %t55 = load ptr, ptr %v22
  %t56 = getelementptr i8, ptr %t55, i64 8
  %t57 = load i32, ptr %t56, !tbaa !12
  %t58 = zext i32 %t57 to i64
  store i64 %t58, ptr %v30
  %t59 = load i64, ptr %v30
  %t60 = icmp sle i64 %t59, 1
  store i1 %t60, ptr %v31
  %t61 = load i1, ptr %v31
  store i1 %t61, ptr %v7
  br label %b2
b9:
  %t62 = load i64, ptr %v32
  %t63 = icmp sgt i64 %t62, 100
  store i1 %t63, ptr %v34
  %t64 = load i1, ptr %v34
  %t65 = and i1 true, %t64
  store i1 %t65, ptr %v35
  %t66 = load i64, ptr %v32
  %t67 = icmp slt i64 %t66, 100
  store i1 %t67, ptr %v37
  %t68 = load i1, ptr %v37
  %t69 = and i1 false, %t68
  store i1 %t69, ptr %v38
  %t70 = load i1, ptr %v35
  %t71 = load i1, ptr %v38
  %t72 = or i1 %t70, %t71
  store i1 %t72, ptr %v39
  %t73 = load i1, ptr %v39
  br i1 %t73, label %b11, label %b10
b10:
  %t74 = load i1, ptr %v6
  br i1 %t74, label %b15, label %b13
b11:
  %t75 = load ptr, ptr %v4
  %t76 = getelementptr i8, ptr %t75, i64 16
  %t77 = load i32, ptr %t76, !tbaa !11
  %t78 = zext i32 %t77 to i64
  store i64 %t78, ptr %v70
  %t79 = load i64, ptr %v70
  %t80 = icmp eq i64 %t79, 9
  store i1 %t80, ptr %v71
  %t81 = load i1, ptr %v71
  br i1 %t81, label %b28, label %b29
b12:
  %t82 = load i64, ptr %v32
  %t83 = add i64 %t82, 1
  %t84 = icmp sgt i64 %t83, 2147483647
  %t85 = icmp slt i64 %t83, -2147483647
  %t86 = or i1 %t84, %t85
  br i1 %t86, label %trap87, label %cont87
trap87:
  store i32 8, ptr @a68_line_no, !tbaa !16
  call void @a68rt_arith_error(i32 0, i32 0)
  unreachable
cont87:
  store i64 %t83, ptr %v68
  %t88 = load i64, ptr %v68
  store i64 %t88, ptr %v32
  br label %b9
b13:
  store i32 8, ptr @a68_line_no, !tbaa !16
  %t89 = load i64, ptr %v32
  %t90 = zext i1 true to i8
  call void @a68rt_set_row_bool(i32 0, i32 1, i32 1, i64 %t89, i64 0, i8 %t90, i32 0)
  store i1 false, ptr %v6
  store i1 false, ptr %v7
  %t91 = load ptr, ptr %v4
  %t92 = getelementptr i8, ptr %t91, i64 16
  %t93 = load i32, ptr %t92, !tbaa !11
  %t94 = zext i32 %t93 to i64
  store i64 %t94, ptr %v51
  %t95 = load i64, ptr %v51
  %t96 = icmp eq i64 %t95, 9
  store i1 %t96, ptr %v52
  %t97 = load i1, ptr %v52
  br i1 %t97, label %b20, label %b19
b14:
  br label %b12
b15:
  %t98 = load i64, ptr %v32
  %t99 = load i64, ptr %v12
  %t100 = icmp sge i64 %t98, %t99
  store i1 %t100, ptr %v40
  %t101 = load i64, ptr %v32
  %t102 = load i64, ptr %v13
  %t103 = icmp sle i64 %t101, %t102
  store i1 %t103, ptr %v41
  %t104 = load i1, ptr %v40
  %t105 = load i1, ptr %v41
  %t106 = and i1 %t104, %t105
  store i1 %t106, ptr %v42
  %t107 = load i1, ptr %v42
  br i1 %t107, label %b17, label %b16
b16:
  store i32 8, ptr @a68_line_no, !tbaa !16
  %t108 = load i64, ptr %v32
  %t109 = load i64, ptr %v12
  %t110 = load i64, ptr %v13
  call void @a68rt_index_error(i64 %t108, i64 %t109, i64 %t110, i32 0)
  unreachable
b17:
  %t111 = load i64, ptr %v32
  %t112 = load i64, ptr %v12
  %t113 = sub i64 %t111, %t112
  store i64 %t113, ptr %v43
  %t114 = load i64, ptr %v43
  %t115 = load i64, ptr %v14
  %t116 = mul i64 %t114, %t115
  store i64 %t116, ptr %v44
  %t117 = load i64, ptr %v10
  %t118 = load i64, ptr %v44
  %t119 = add i64 %t117, %t118
  store i64 %t119, ptr %v45
  %t120 = load i1, ptr %v7
  br i1 %t120, label %b18, label %b13
b18:
  %t121 = load i64, ptr %v11
  %t122 = mul i64 %t121, 1
  store i64 %t122, ptr %v46
  %t123 = load i64, ptr %v46
  %t124 = load i64, ptr %v45
  %t125 = add i64 %t123, %t124
  store i64 %t125, ptr %v47
  %t126 = load i64, ptr %v47
  %t127 = add i64 %t126, 24
  store i64 %t127, ptr %v48
  %t128 = load ptr, ptr %v9
  %t129 = load i64, ptr %v48
  %t130 = getelementptr i8, ptr %t128, i64 %t129
  %t131 = trunc i64 1 to i8
  store i8 %t131, ptr %t130, !tbaa !13
  %t132 = load i64, ptr %v45
  %t133 = mul i64 %t132, 1
  store i64 %t133, ptr %v49
  %t134 = load i64, ptr %v49
  %t135 = add i64 %t134, 24
  store i64 %t135, ptr %v50
  %t136 = load ptr, ptr %v9
  %t137 = load i64, ptr %v50
  %t138 = getelementptr i8, ptr %t136, i64 %t137
  %t139 = zext i1 true to i64
  %t140 = trunc i64 %t139 to i8
  store i8 %t140, ptr %t138, !tbaa !13
  br label %b14
b19:
  br label %b14
b20:
  %t141 = load ptr, ptr %v4
  %t142 = getelementptr i8, ptr %t141, i64 24
  %t143 = load ptr, ptr %t142, !tbaa !11
  store ptr %t143, ptr %v53
  %t144 = load ptr, ptr %v53
  %t145 = getelementptr i8, ptr %t144, i64 40
  %t146 = load i32, ptr %t145, !tbaa !12
  %t147 = zext i32 %t146 to i64
  store i64 %t147, ptr %v54
  %t148 = load i64, ptr %v54
  %t149 = icmp eq i64 %t148, 0
  store i1 %t149, ptr %v55
  %t150 = load i1, ptr %v55
  br i1 %t150, label %b21, label %b19
b21:
  store i64 0, ptr %v10
  store i64 1, ptr %v12
  store i64 100, ptr %v13
  store i64 1, ptr %v14
  %t151 = load ptr, ptr %v53
  %t152 = getelementptr i8, ptr %t151, i64 24
  %t153 = load ptr, ptr %t152, !tbaa !12
  store ptr %t153, ptr %v56
  %t154 = load ptr, ptr %v56
  %t155 = getelementptr i8, ptr %t154, i64 0
  %t156 = load i8, ptr %t155, !tbaa !12
  %t157 = zext i8 %t156 to i64
  store i64 %t157, ptr %v57
  %t158 = load ptr, ptr %v56
  store ptr %t158, ptr %v58
  %t159 = load i64, ptr %v57
  %t160 = icmp eq i64 %t159, 3
  store i1 %t160, ptr %v59
  %t161 = load i1, ptr %v59
  br i1 %t161, label %b22, label %b23
b22:
  %t162 = load ptr, ptr %v56
  %t163 = getelementptr i8, ptr %t162, i64 24
  %t164 = load ptr, ptr %t163, !tbaa !12
  store ptr %t164, ptr %v60
  %t165 = load ptr, ptr %v60
  store ptr %t165, ptr %v58
  br label %b23
b23:
  %t166 = load ptr, ptr %v58
  store ptr %t166, ptr %v9
  %t167 = load ptr, ptr %v58
  %t168 = getelementptr i8, ptr %t167, i64 0
  %t169 = load i8, ptr %t168, !tbaa !12
  %t170 = zext i8 %t169 to i64
  store i64 %t170, ptr %v61
  %t171 = load i64, ptr %v61
  %t172 = icmp eq i64 %t171, 2
  store i1 %t172, ptr %v62
  %t173 = load i1, ptr %v62
  br i1 %t173, label %b24, label %b19
b24:
  %t174 = load ptr, ptr %v58
  %t175 = getelementptr i8, ptr %t174, i64 2
  %t176 = load i16, ptr %t175, !tbaa !12
  %t177 = zext i16 %t176 to i64
  store i64 %t177, ptr %v63
  %t178 = load i64, ptr %v63
  %t179 = icmp eq i64 %t178, 3
  store i1 %t179, ptr %v64
  %t180 = load i1, ptr %v64
  br i1 %t180, label %b25, label %b19
b25:
  %t181 = load ptr, ptr %v58
  %t182 = getelementptr i8, ptr %t181, i64 4
  %t183 = load i32, ptr %t182, !tbaa !12
  %t184 = zext i32 %t183 to i64
  store i64 %t184, ptr %v65
  %t185 = load i64, ptr %v65
  store i64 %t185, ptr %v11
  store i1 true, ptr %v6
  %t186 = load ptr, ptr %v58
  %t187 = getelementptr i8, ptr %t186, i64 8
  %t188 = load i32, ptr %t187, !tbaa !12
  %t189 = zext i32 %t188 to i64
  store i64 %t189, ptr %v66
  %t190 = load i64, ptr %v66
  %t191 = icmp sle i64 %t190, 1
  store i1 %t191, ptr %v67
  %t192 = load i1, ptr %v67
  store i1 %t192, ptr %v7
  br label %b19
b26:
  store i32 8, ptr @a68_line_no, !tbaa !16
  %t193 = zext i1 false to i8
  call void @a68rt_set_row_bool(i32 0, i32 1, i32 1, i64 1, i64 0, i8 %t193, i32 0)
  br label %b27
b27:
  store i1 false, ptr %v108
  store i1 false, ptr %v109
  %t194 = load ptr, ptr %v4
  %t195 = getelementptr i8, ptr %t194, i64 16
  %t196 = load i32, ptr %t195, !tbaa !11
  %t197 = zext i32 %t196 to i64
  store i64 %t197, ptr %v117
  %t198 = load i64, ptr %v117
  %t199 = icmp eq i64 %t198, 9
  store i1 %t199, ptr %v118
  %t200 = load i1, ptr %v118
  br i1 %t200, label %b43, label %b42
b28:
  %t201 = load ptr, ptr %v4
  %t202 = getelementptr i8, ptr %t201, i64 24
  %t203 = load ptr, ptr %t202, !tbaa !11
  store ptr %t203, ptr %v72
  %t204 = load ptr, ptr %v72
  store ptr %t204, ptr %v69
  br label %b30
b29:
  %t205 = load i64, ptr %v70
  %t206 = icmp eq i64 %t205, 8
  store i1 %t206, ptr %v73
  %t207 = load i1, ptr %v73
  br i1 %t207, label %b31, label %b26
b30:
  %t208 = load ptr, ptr %v69
  %t209 = getelementptr i8, ptr %t208, i64 40
  %t210 = load i32, ptr %t209, !tbaa !12
  %t211 = zext i32 %t210 to i64
  store i64 %t211, ptr %v79
  %t212 = load i64, ptr %v79
  %t213 = icmp eq i64 %t212, 0
  store i1 %t213, ptr %v80
  %t214 = load i1, ptr %v80
  br i1 %t214, label %b34, label %b26
b31:
  %t215 = load ptr, ptr %v4
  %t216 = getelementptr i8, ptr %t215, i64 20
  %t217 = load i32, ptr %t216, !tbaa !11
  %t218 = zext i32 %t217 to i64
  store i64 %t218, ptr %v74
  %t219 = load i64, ptr %v74
  %t220 = icmp eq i64 %t219, 4294967295
  store i1 %t220, ptr %v75
  %t221 = load i1, ptr %v75
  br i1 %t221, label %b32, label %b26
b32:
  %t222 = load ptr, ptr %v4
  %t223 = getelementptr i8, ptr %t222, i64 24
  %t224 = load ptr, ptr %t223, !tbaa !11
  store ptr %t224, ptr %v76
  %t225 = load ptr, ptr %v76
  %t226 = getelementptr i8, ptr %t225, i64 0
  %t227 = load i8, ptr %t226, !tbaa !12
  %t228 = zext i8 %t227 to i64
  store i64 %t228, ptr %v77
  %t229 = load i64, ptr %v77
  %t230 = icmp eq i64 %t229, 3
  store i1 %t230, ptr %v78
  %t231 = load i1, ptr %v78
  br i1 %t231, label %b33, label %b26
b33:
  %t232 = load ptr, ptr %v76
  store ptr %t232, ptr %v69
  br label %b30
b34:
  %t233 = load ptr, ptr %v69
  %t234 = getelementptr i8, ptr %t233, i64 32
  %t235 = load i64, ptr %t234, !tbaa !12
  store i64 %t235, ptr %v81
  %t236 = load ptr, ptr %v69
  %t237 = getelementptr i8, ptr %t236, i64 48
  %t238 = load i64, ptr %t237, !tbaa !12
  store i64 %t238, ptr %v82
  %t239 = load ptr, ptr %v69
  %t240 = getelementptr i8, ptr %t239, i64 56
  %t241 = load i64, ptr %t240, !tbaa !12
  store i64 %t241, ptr %v83
  %t242 = load ptr, ptr %v69
  %t243 = getelementptr i8, ptr %t242, i64 64
  %t244 = load i64, ptr %t243, !tbaa !12
  store i64 %t244, ptr %v84
  %t245 = load i64, ptr %v82
  %t246 = icmp sge i64 1, %t245
  store i1 %t246, ptr %v85
  %t247 = load i64, ptr %v83
  %t248 = icmp sle i64 1, %t247
  store i1 %t248, ptr %v86
  %t249 = load i1, ptr %v85
  %t250 = load i1, ptr %v86
  %t251 = and i1 %t249, %t250
  store i1 %t251, ptr %v87
  %t252 = load i1, ptr %v87
  br i1 %t252, label %b36, label %b35
b35:
  store i32 9, ptr @a68_line_no, !tbaa !16
  %t253 = load i64, ptr %v82
  %t254 = load i64, ptr %v83
  call void @a68rt_index_error(i64 1, i64 %t253, i64 %t254, i32 0)
  unreachable
b36:
  %t255 = load i64, ptr %v82
  %t256 = sub i64 1, %t255
  store i64 %t256, ptr %v88
  %t257 = load i64, ptr %v88
  %t258 = load i64, ptr %v84
  %t259 = mul i64 %t257, %t258
  store i64 %t259, ptr %v89
  %t260 = load i64, ptr %v81
  %t261 = load i64, ptr %v89
  %t262 = add i64 %t260, %t261
  store i64 %t262, ptr %v90
  %t263 = load ptr, ptr %v69
  %t264 = getelementptr i8, ptr %t263, i64 24
  %t265 = load ptr, ptr %t264, !tbaa !12
  store ptr %t265, ptr %v91
  %t266 = load ptr, ptr %v91
  %t267 = getelementptr i8, ptr %t266, i64 0
  %t268 = load i8, ptr %t267, !tbaa !12
  %t269 = zext i8 %t268 to i64
  store i64 %t269, ptr %v92
  %t270 = load ptr, ptr %v91
  store ptr %t270, ptr %v93
  %t271 = load i64, ptr %v92
  %t272 = icmp eq i64 %t271, 3
  store i1 %t272, ptr %v94
  %t273 = load i1, ptr %v94
  br i1 %t273, label %b37, label %b38
b37:
  %t274 = load ptr, ptr %v91
  %t275 = getelementptr i8, ptr %t274, i64 24
  %t276 = load ptr, ptr %t275, !tbaa !12
  store ptr %t276, ptr %v95
  %t277 = load ptr, ptr %v95
  store ptr %t277, ptr %v93
  br label %b38
b38:
  %t278 = load ptr, ptr %v93
  %t279 = getelementptr i8, ptr %t278, i64 0
  %t280 = load i8, ptr %t279, !tbaa !12
  %t281 = zext i8 %t280 to i64
  store i64 %t281, ptr %v96
  %t282 = load i64, ptr %v96
  %t283 = icmp eq i64 %t282, 2
  store i1 %t283, ptr %v97
  %t284 = load i1, ptr %v97
  br i1 %t284, label %b39, label %b26
b39:
  %t285 = load ptr, ptr %v93
  %t286 = getelementptr i8, ptr %t285, i64 2
  %t287 = load i16, ptr %t286, !tbaa !12
  %t288 = zext i16 %t287 to i64
  store i64 %t288, ptr %v98
  %t289 = load i64, ptr %v98
  %t290 = icmp eq i64 %t289, 3
  store i1 %t290, ptr %v99
  %t291 = load i1, ptr %v99
  br i1 %t291, label %b40, label %b26
b40:
  %t292 = load ptr, ptr %v93
  %t293 = getelementptr i8, ptr %t292, i64 8
  %t294 = load i32, ptr %t293, !tbaa !12
  %t295 = zext i32 %t294 to i64
  store i64 %t295, ptr %v100
  %t296 = load i64, ptr %v100
  %t297 = icmp sle i64 %t296, 1
  store i1 %t297, ptr %v101
  %t298 = load i1, ptr %v101
  br i1 %t298, label %b41, label %b26
b41:
  %t299 = load ptr, ptr %v93
  %t300 = getelementptr i8, ptr %t299, i64 4
  %t301 = load i32, ptr %t300, !tbaa !12
  %t302 = zext i32 %t301 to i64
  store i64 %t302, ptr %v102
  %t303 = load i64, ptr %v102
  %t304 = mul i64 %t303, 1
  store i64 %t304, ptr %v103
  %t305 = load i64, ptr %v103
  %t306 = load i64, ptr %v90
  %t307 = add i64 %t305, %t306
  store i64 %t307, ptr %v104
  %t308 = load i64, ptr %v104
  %t309 = add i64 %t308, 24
  store i64 %t309, ptr %v105
  %t310 = load ptr, ptr %v93
  %t311 = load i64, ptr %v105
  %t312 = getelementptr i8, ptr %t310, i64 %t311
  %t313 = trunc i64 1 to i8
  store i8 %t313, ptr %t312, !tbaa !13
  %t314 = load i64, ptr %v90
  %t315 = mul i64 %t314, 1
  store i64 %t315, ptr %v106
  %t316 = load i64, ptr %v106
  %t317 = add i64 %t316, 24
  store i64 %t317, ptr %v107
  %t318 = load ptr, ptr %v93
  %t319 = load i64, ptr %v107
  %t320 = getelementptr i8, ptr %t318, i64 %t319
  %t321 = zext i1 false to i64
  %t322 = trunc i64 %t321 to i8
  store i8 %t322, ptr %t320, !tbaa !13
  br label %b27
b42:
  store i64 2, ptr %v134
  br label %b49
b43:
  %t323 = load ptr, ptr %v4
  %t324 = getelementptr i8, ptr %t323, i64 24
  %t325 = load ptr, ptr %t324, !tbaa !11
  store ptr %t325, ptr %v119
  %t326 = load ptr, ptr %v119
  %t327 = getelementptr i8, ptr %t326, i64 40
  %t328 = load i32, ptr %t327, !tbaa !12
  %t329 = zext i32 %t328 to i64
  store i64 %t329, ptr %v120
  %t330 = load i64, ptr %v120
  %t331 = icmp eq i64 %t330, 0
  store i1 %t331, ptr %v121
  %t332 = load i1, ptr %v121
  br i1 %t332, label %b44, label %b42
b44:
  store i64 0, ptr %v112
  store i64 1, ptr %v114
  store i64 100, ptr %v115
  store i64 1, ptr %v116
  %t333 = load ptr, ptr %v119
  %t334 = getelementptr i8, ptr %t333, i64 24
  %t335 = load ptr, ptr %t334, !tbaa !12
  store ptr %t335, ptr %v122
  %t336 = load ptr, ptr %v122
  %t337 = getelementptr i8, ptr %t336, i64 0
  %t338 = load i8, ptr %t337, !tbaa !12
  %t339 = zext i8 %t338 to i64
  store i64 %t339, ptr %v123
  %t340 = load ptr, ptr %v122
  store ptr %t340, ptr %v124
  %t341 = load i64, ptr %v123
  %t342 = icmp eq i64 %t341, 3
  store i1 %t342, ptr %v125
  %t343 = load i1, ptr %v125
  br i1 %t343, label %b45, label %b46
b45:
  %t344 = load ptr, ptr %v122
  %t345 = getelementptr i8, ptr %t344, i64 24
  %t346 = load ptr, ptr %t345, !tbaa !12
  store ptr %t346, ptr %v126
  %t347 = load ptr, ptr %v126
  store ptr %t347, ptr %v124
  br label %b46
b46:
  %t348 = load ptr, ptr %v124
  store ptr %t348, ptr %v111
  %t349 = load ptr, ptr %v124
  %t350 = getelementptr i8, ptr %t349, i64 0
  %t351 = load i8, ptr %t350, !tbaa !12
  %t352 = zext i8 %t351 to i64
  store i64 %t352, ptr %v127
  %t353 = load i64, ptr %v127
  %t354 = icmp eq i64 %t353, 2
  store i1 %t354, ptr %v128
  %t355 = load i1, ptr %v128
  br i1 %t355, label %b47, label %b42
b47:
  %t356 = load ptr, ptr %v124
  %t357 = getelementptr i8, ptr %t356, i64 2
  %t358 = load i16, ptr %t357, !tbaa !12
  %t359 = zext i16 %t358 to i64
  store i64 %t359, ptr %v129
  %t360 = load i64, ptr %v129
  %t361 = icmp eq i64 %t360, 3
  store i1 %t361, ptr %v130
  %t362 = load i1, ptr %v130
  br i1 %t362, label %b48, label %b42
b48:
  %t363 = load ptr, ptr %v124
  %t364 = getelementptr i8, ptr %t363, i64 4
  %t365 = load i32, ptr %t364, !tbaa !12
  %t366 = zext i32 %t365 to i64
  store i64 %t366, ptr %v131
  %t367 = load i64, ptr %v131
  store i64 %t367, ptr %v113
  store i1 true, ptr %v108
  %t368 = load ptr, ptr %v124
  %t369 = getelementptr i8, ptr %t368, i64 8
  %t370 = load i32, ptr %t369, !tbaa !12
  %t371 = zext i32 %t370 to i64
  store i64 %t371, ptr %v132
  %t372 = load i64, ptr %v132
  %t373 = icmp sle i64 %t372, 1
  store i1 %t373, ptr %v133
  %t374 = load i1, ptr %v133
  store i1 %t374, ptr %v109
  br label %b42
b49:
  %t375 = load i64, ptr %v134
  %t376 = icmp sgt i64 %t375, 100
  store i1 %t376, ptr %v136
  %t377 = load i1, ptr %v136
  %t378 = and i1 true, %t377
  store i1 %t378, ptr %v137
  %t379 = load i64, ptr %v134
  %t380 = icmp slt i64 %t379, 100
  store i1 %t380, ptr %v139
  %t381 = load i1, ptr %v139
  %t382 = and i1 false, %t381
  store i1 %t382, ptr %v140
  %t383 = load i1, ptr %v137
  %t384 = load i1, ptr %v140
  %t385 = or i1 %t383, %t384
  store i1 %t385, ptr %v141
  %t386 = load i1, ptr %v141
  br i1 %t386, label %b51, label %b50
b50:
  %t387 = load i1, ptr %v108
  br i1 %t387, label %b55, label %b53
b51:
  store i64 0, ptr %v2
  store i64 0, ptr %v3
  store i64 1, ptr %v215
  br label %b93
b52:
  %t388 = load i64, ptr %v134
  %t389 = add i64 %t388, 1
  %t390 = icmp sgt i64 %t389, 2147483647
  %t391 = icmp slt i64 %t389, -2147483647
  %t392 = or i1 %t390, %t391
  br i1 %t392, label %trap393, label %cont393
trap393:
  store i32 16, ptr @a68_line_no, !tbaa !16
  call void @a68rt_arith_error(i32 0, i32 0)
  unreachable
cont393:
  store i64 %t389, ptr %v212
  %t394 = load i64, ptr %v212
  store i64 %t394, ptr %v134
  br label %b49
b53:
  store i32 16, ptr @a68_line_no, !tbaa !16
  %t395 = load i64, ptr %v134
  %t396 = call i8 @a68rt_row_bool(i32 0, i32 1, i32 1, i64 %t395, i64 0, i32 0)
  %t397 = icmp ne i8 %t396, 0
  store i1 %t397, ptr %v158
  %t398 = load i1, ptr %v158
  store i1 %t398, ptr %v142
  store i1 false, ptr %v108
  store i1 false, ptr %v109
  %t399 = load ptr, ptr %v4
  %t400 = getelementptr i8, ptr %t399, i64 16
  %t401 = load i32, ptr %t400, !tbaa !11
  %t402 = zext i32 %t401 to i64
  store i64 %t402, ptr %v159
  %t403 = load i64, ptr %v159
  %t404 = icmp eq i64 %t403, 9
  store i1 %t404, ptr %v160
  %t405 = load i1, ptr %v160
  br i1 %t405, label %b61, label %b60
b54:
  %t406 = load i1, ptr %v142
  br i1 %t406, label %b67, label %b68
b55:
  %t407 = load i64, ptr %v134
  %t408 = load i64, ptr %v114
  %t409 = icmp sge i64 %t407, %t408
  store i1 %t409, ptr %v143
  %t410 = load i64, ptr %v134
  %t411 = load i64, ptr %v115
  %t412 = icmp sle i64 %t410, %t411
  store i1 %t412, ptr %v144
  %t413 = load i1, ptr %v143
  %t414 = load i1, ptr %v144
  %t415 = and i1 %t413, %t414
  store i1 %t415, ptr %v145
  %t416 = load i1, ptr %v145
  br i1 %t416, label %b57, label %b56
b56:
  store i32 16, ptr @a68_line_no, !tbaa !16
  %t417 = load i64, ptr %v134
  %t418 = load i64, ptr %v114
  %t419 = load i64, ptr %v115
  call void @a68rt_index_error(i64 %t417, i64 %t418, i64 %t419, i32 0)
  unreachable
b57:
  %t420 = load i64, ptr %v134
  %t421 = load i64, ptr %v114
  %t422 = sub i64 %t420, %t421
  store i64 %t422, ptr %v146
  %t423 = load i64, ptr %v146
  %t424 = load i64, ptr %v116
  %t425 = mul i64 %t423, %t424
  store i64 %t425, ptr %v147
  %t426 = load i64, ptr %v112
  %t427 = load i64, ptr %v147
  %t428 = add i64 %t426, %t427
  store i64 %t428, ptr %v148
  %t429 = load i64, ptr %v113
  %t430 = mul i64 %t429, 1
  store i64 %t430, ptr %v149
  %t431 = load i64, ptr %v149
  %t432 = load i64, ptr %v148
  %t433 = add i64 %t431, %t432
  store i64 %t433, ptr %v150
  %t434 = load i64, ptr %v150
  %t435 = add i64 %t434, 24
  store i64 %t435, ptr %v151
  %t436 = load ptr, ptr %v111
  %t437 = load i64, ptr %v151
  %t438 = getelementptr i8, ptr %t436, i64 %t437
  %t439 = load i8, ptr %t438, !tbaa !13
  %t440 = zext i8 %t439 to i64
  store i64 %t440, ptr %v152
  %t441 = load i64, ptr %v152
  %t442 = icmp ne i64 %t441, 0
  store i1 %t442, ptr %v153
  %t443 = load i1, ptr %v153
  br i1 %t443, label %b59, label %b58
b58:
  store i32 16, ptr @a68_line_no, !tbaa !16
  call void @a68rt_undef_error(i32 2, i32 0)
  unreachable
b59:
  %t444 = load i64, ptr %v148
  %t445 = mul i64 %t444, 1
  store i64 %t445, ptr %v154
  %t446 = load i64, ptr %v154
  %t447 = add i64 %t446, 24
  store i64 %t447, ptr %v155
  %t448 = load ptr, ptr %v111
  %t449 = load i64, ptr %v155
  %t450 = getelementptr i8, ptr %t448, i64 %t449
  %t451 = load i8, ptr %t450, !tbaa !13
  %t452 = zext i8 %t451 to i64
  store i64 %t452, ptr %v156
  %t453 = load i64, ptr %v156
  %t454 = icmp ne i64 %t453, 0
  store i1 %t454, ptr %v157
  %t455 = load i1, ptr %v157
  store i1 %t455, ptr %v142
  br label %b54
b60:
  br label %b54
b61:
  %t456 = load ptr, ptr %v4
  %t457 = getelementptr i8, ptr %t456, i64 24
  %t458 = load ptr, ptr %t457, !tbaa !11
  store ptr %t458, ptr %v161
  %t459 = load ptr, ptr %v161
  %t460 = getelementptr i8, ptr %t459, i64 40
  %t461 = load i32, ptr %t460, !tbaa !12
  %t462 = zext i32 %t461 to i64
  store i64 %t462, ptr %v162
  %t463 = load i64, ptr %v162
  %t464 = icmp eq i64 %t463, 0
  store i1 %t464, ptr %v163
  %t465 = load i1, ptr %v163
  br i1 %t465, label %b62, label %b60
b62:
  store i64 0, ptr %v112
  store i64 1, ptr %v114
  store i64 100, ptr %v115
  store i64 1, ptr %v116
  %t466 = load ptr, ptr %v161
  %t467 = getelementptr i8, ptr %t466, i64 24
  %t468 = load ptr, ptr %t467, !tbaa !12
  store ptr %t468, ptr %v164
  %t469 = load ptr, ptr %v164
  %t470 = getelementptr i8, ptr %t469, i64 0
  %t471 = load i8, ptr %t470, !tbaa !12
  %t472 = zext i8 %t471 to i64
  store i64 %t472, ptr %v165
  %t473 = load ptr, ptr %v164
  store ptr %t473, ptr %v166
  %t474 = load i64, ptr %v165
  %t475 = icmp eq i64 %t474, 3
  store i1 %t475, ptr %v167
  %t476 = load i1, ptr %v167
  br i1 %t476, label %b63, label %b64
b63:
  %t477 = load ptr, ptr %v164
  %t478 = getelementptr i8, ptr %t477, i64 24
  %t479 = load ptr, ptr %t478, !tbaa !12
  store ptr %t479, ptr %v168
  %t480 = load ptr, ptr %v168
  store ptr %t480, ptr %v166
  br label %b64
b64:
  %t481 = load ptr, ptr %v166
  store ptr %t481, ptr %v111
  %t482 = load ptr, ptr %v166
  %t483 = getelementptr i8, ptr %t482, i64 0
  %t484 = load i8, ptr %t483, !tbaa !12
  %t485 = zext i8 %t484 to i64
  store i64 %t485, ptr %v169
  %t486 = load i64, ptr %v169
  %t487 = icmp eq i64 %t486, 2
  store i1 %t487, ptr %v170
  %t488 = load i1, ptr %v170
  br i1 %t488, label %b65, label %b60
b65:
  %t489 = load ptr, ptr %v166
  %t490 = getelementptr i8, ptr %t489, i64 2
  %t491 = load i16, ptr %t490, !tbaa !12
  %t492 = zext i16 %t491 to i64
  store i64 %t492, ptr %v171
  %t493 = load i64, ptr %v171
  %t494 = icmp eq i64 %t493, 3
  store i1 %t494, ptr %v172
  %t495 = load i1, ptr %v172
  br i1 %t495, label %b66, label %b60
b66:
  %t496 = load ptr, ptr %v166
  %t497 = getelementptr i8, ptr %t496, i64 4
  %t498 = load i32, ptr %t497, !tbaa !12
  %t499 = zext i32 %t498 to i64
  store i64 %t499, ptr %v173
  %t500 = load i64, ptr %v173
  store i64 %t500, ptr %v113
  store i1 true, ptr %v108
  %t501 = load ptr, ptr %v166
  %t502 = getelementptr i8, ptr %t501, i64 8
  %t503 = load i32, ptr %t502, !tbaa !12
  %t504 = zext i32 %t503 to i64
  store i64 %t504, ptr %v174
  %t505 = load i64, ptr %v174
  %t506 = icmp sle i64 %t505, 1
  store i1 %t506, ptr %v175
  %t507 = load i1, ptr %v175
  store i1 %t507, ptr %v109
  br label %b60
b67:
  %t508 = load i64, ptr %v134
  %t509 = load i64, ptr %v134
  %t510 = add i64 %t508, %t509
  %t511 = icmp sgt i64 %t510, 2147483647
  %t512 = icmp slt i64 %t510, -2147483647
  %t513 = or i1 %t511, %t512
  br i1 %t513, label %trap514, label %cont514
trap514:
  store i32 11, ptr @a68_line_no, !tbaa !16
  call void @a68rt_arith_error(i32 0, i32 0)
  unreachable
cont514:
  store i64 %t510, ptr %v178
  %t515 = load i64, ptr %v178
  store i64 %t515, ptr %v176
  store i64 1, ptr %v179
  br label %b71
b68:
  br label %b69
b69:
  br label %b52
b70:
  br label %b69
b71:
  br label %b72
b72:
  %t516 = load i64, ptr %v176
  %t517 = icmp sle i64 %t516, 100
  store i1 %t517, ptr %v181
  %t518 = load i1, ptr %v181
  br i1 %t518, label %b75, label %b76
b73:
  br label %b70
b74:
  %t519 = load i64, ptr %v179
  %t520 = add i64 %t519, 1
  %t521 = icmp sgt i64 %t520, 2147483647
  %t522 = icmp slt i64 %t520, -2147483647
  %t523 = or i1 %t521, %t522
  br i1 %t523, label %trap524, label %cont524
trap524:
  store i32 12, ptr @a68_line_no, !tbaa !16
  call void @a68rt_arith_error(i32 0, i32 0)
  unreachable
cont524:
  store i64 %t520, ptr %v211
  %t525 = load i64, ptr %v211
  store i64 %t525, ptr %v179
  br label %b71
b75:
  %t526 = load i1, ptr %v108
  br i1 %t526, label %b80, label %b78
b76:
  store i1 false, ptr %v180
  br label %b77
b77:
  %t527 = load i1, ptr %v180
  br i1 %t527, label %b91, label %b92
b78:
  store i32 12, ptr @a68_line_no, !tbaa !16
  %t528 = load i64, ptr %v176
  %t529 = zext i1 false to i8
  call void @a68rt_set_row_bool(i32 0, i32 1, i32 1, i64 %t528, i64 0, i8 %t529, i32 0)
  store i1 false, ptr %v108
  store i1 false, ptr %v109
  %t530 = load ptr, ptr %v4
  %t531 = getelementptr i8, ptr %t530, i64 16
  %t532 = load i32, ptr %t531, !tbaa !11
  %t533 = zext i32 %t532 to i64
  store i64 %t533, ptr %v193
  %t534 = load i64, ptr %v193
  %t535 = icmp eq i64 %t534, 9
  store i1 %t535, ptr %v194
  %t536 = load i1, ptr %v194
  br i1 %t536, label %b85, label %b84
b79:
  %t537 = load i64, ptr %v176
  %t538 = load i64, ptr %v134
  %t539 = add i64 %t537, %t538
  %t540 = icmp sgt i64 %t539, 2147483647
  %t541 = icmp slt i64 %t539, -2147483647
  %t542 = or i1 %t540, %t541
  br i1 %t542, label %trap543, label %cont543
trap543:
  store i32 12, ptr @a68_line_no, !tbaa !16
  call void @a68rt_arith_error(i32 0, i32 0)
  unreachable
cont543:
  store i64 %t539, ptr %v210
  %t544 = load i64, ptr %v210
  store i64 %t544, ptr %v176
  store i1 true, ptr %v180
  br label %b77
b80:
  %t545 = load i64, ptr %v176
  %t546 = load i64, ptr %v114
  %t547 = icmp sge i64 %t545, %t546
  store i1 %t547, ptr %v182
  %t548 = load i64, ptr %v176
  %t549 = load i64, ptr %v115
  %t550 = icmp sle i64 %t548, %t549
  store i1 %t550, ptr %v183
  %t551 = load i1, ptr %v182
  %t552 = load i1, ptr %v183
  %t553 = and i1 %t551, %t552
  store i1 %t553, ptr %v184
  %t554 = load i1, ptr %v184
  br i1 %t554, label %b82, label %b81
b81:
  store i32 12, ptr @a68_line_no, !tbaa !16
  %t555 = load i64, ptr %v176
  %t556 = load i64, ptr %v114
  %t557 = load i64, ptr %v115
  call void @a68rt_index_error(i64 %t555, i64 %t556, i64 %t557, i32 0)
  unreachable
b82:
  %t558 = load i64, ptr %v176
  %t559 = load i64, ptr %v114
  %t560 = sub i64 %t558, %t559
  store i64 %t560, ptr %v185
  %t561 = load i64, ptr %v185
  %t562 = load i64, ptr %v116
  %t563 = mul i64 %t561, %t562
  store i64 %t563, ptr %v186
  %t564 = load i64, ptr %v112
  %t565 = load i64, ptr %v186
  %t566 = add i64 %t564, %t565
  store i64 %t566, ptr %v187
  %t567 = load i1, ptr %v109
  br i1 %t567, label %b83, label %b78
b83:
  %t568 = load i64, ptr %v113
  %t569 = mul i64 %t568, 1
  store i64 %t569, ptr %v188
  %t570 = load i64, ptr %v188
  %t571 = load i64, ptr %v187
  %t572 = add i64 %t570, %t571
  store i64 %t572, ptr %v189
  %t573 = load i64, ptr %v189
  %t574 = add i64 %t573, 24
  store i64 %t574, ptr %v190
  %t575 = load ptr, ptr %v111
  %t576 = load i64, ptr %v190
  %t577 = getelementptr i8, ptr %t575, i64 %t576
  %t578 = trunc i64 1 to i8
  store i8 %t578, ptr %t577, !tbaa !13
  %t579 = load i64, ptr %v187
  %t580 = mul i64 %t579, 1
  store i64 %t580, ptr %v191
  %t581 = load i64, ptr %v191
  %t582 = add i64 %t581, 24
  store i64 %t582, ptr %v192
  %t583 = load ptr, ptr %v111
  %t584 = load i64, ptr %v192
  %t585 = getelementptr i8, ptr %t583, i64 %t584
  %t586 = zext i1 false to i64
  %t587 = trunc i64 %t586 to i8
  store i8 %t587, ptr %t585, !tbaa !13
  br label %b79
b84:
  br label %b79
b85:
  %t588 = load ptr, ptr %v4
  %t589 = getelementptr i8, ptr %t588, i64 24
  %t590 = load ptr, ptr %t589, !tbaa !11
  store ptr %t590, ptr %v195
  %t591 = load ptr, ptr %v195
  %t592 = getelementptr i8, ptr %t591, i64 40
  %t593 = load i32, ptr %t592, !tbaa !12
  %t594 = zext i32 %t593 to i64
  store i64 %t594, ptr %v196
  %t595 = load i64, ptr %v196
  %t596 = icmp eq i64 %t595, 0
  store i1 %t596, ptr %v197
  %t597 = load i1, ptr %v197
  br i1 %t597, label %b86, label %b84
b86:
  store i64 0, ptr %v112
  store i64 1, ptr %v114
  store i64 100, ptr %v115
  store i64 1, ptr %v116
  %t598 = load ptr, ptr %v195
  %t599 = getelementptr i8, ptr %t598, i64 24
  %t600 = load ptr, ptr %t599, !tbaa !12
  store ptr %t600, ptr %v198
  %t601 = load ptr, ptr %v198
  %t602 = getelementptr i8, ptr %t601, i64 0
  %t603 = load i8, ptr %t602, !tbaa !12
  %t604 = zext i8 %t603 to i64
  store i64 %t604, ptr %v199
  %t605 = load ptr, ptr %v198
  store ptr %t605, ptr %v200
  %t606 = load i64, ptr %v199
  %t607 = icmp eq i64 %t606, 3
  store i1 %t607, ptr %v201
  %t608 = load i1, ptr %v201
  br i1 %t608, label %b87, label %b88
b87:
  %t609 = load ptr, ptr %v198
  %t610 = getelementptr i8, ptr %t609, i64 24
  %t611 = load ptr, ptr %t610, !tbaa !12
  store ptr %t611, ptr %v202
  %t612 = load ptr, ptr %v202
  store ptr %t612, ptr %v200
  br label %b88
b88:
  %t613 = load ptr, ptr %v200
  store ptr %t613, ptr %v111
  %t614 = load ptr, ptr %v200
  %t615 = getelementptr i8, ptr %t614, i64 0
  %t616 = load i8, ptr %t615, !tbaa !12
  %t617 = zext i8 %t616 to i64
  store i64 %t617, ptr %v203
  %t618 = load i64, ptr %v203
  %t619 = icmp eq i64 %t618, 2
  store i1 %t619, ptr %v204
  %t620 = load i1, ptr %v204
  br i1 %t620, label %b89, label %b84
b89:
  %t621 = load ptr, ptr %v200
  %t622 = getelementptr i8, ptr %t621, i64 2
  %t623 = load i16, ptr %t622, !tbaa !12
  %t624 = zext i16 %t623 to i64
  store i64 %t624, ptr %v205
  %t625 = load i64, ptr %v205
  %t626 = icmp eq i64 %t625, 3
  store i1 %t626, ptr %v206
  %t627 = load i1, ptr %v206
  br i1 %t627, label %b90, label %b84
b90:
  %t628 = load ptr, ptr %v200
  %t629 = getelementptr i8, ptr %t628, i64 4
  %t630 = load i32, ptr %t629, !tbaa !12
  %t631 = zext i32 %t630 to i64
  store i64 %t631, ptr %v207
  %t632 = load i64, ptr %v207
  store i64 %t632, ptr %v113
  store i1 true, ptr %v108
  %t633 = load ptr, ptr %v200
  %t634 = getelementptr i8, ptr %t633, i64 8
  %t635 = load i32, ptr %t634, !tbaa !12
  %t636 = zext i32 %t635 to i64
  store i64 %t636, ptr %v208
  %t637 = load i64, ptr %v208
  %t638 = icmp sle i64 %t637, 1
  store i1 %t638, ptr %v209
  %t639 = load i1, ptr %v209
  store i1 %t639, ptr %v109
  br label %b84
b91:
  br label %b74
b92:
  br label %b73
b93:
  %t640 = load i64, ptr %v215
  %t641 = icmp sgt i64 %t640, 100
  store i1 %t641, ptr %v217
  %t642 = load i1, ptr %v217
  %t643 = and i1 true, %t642
  store i1 %t643, ptr %v218
  %t644 = load i64, ptr %v215
  %t645 = icmp slt i64 %t644, 100
  store i1 %t645, ptr %v220
  %t646 = load i1, ptr %v220
  %t647 = and i1 false, %t646
  store i1 %t647, ptr %v221
  %t648 = load i1, ptr %v218
  %t649 = load i1, ptr %v221
  %t650 = or i1 %t648, %t649
  store i1 %t650, ptr %v222
  %t651 = load i1, ptr %v222
  br i1 %t651, label %b95, label %b94
b94:
  store i32 12, ptr @a68_line_no, !tbaa !16
  %t652 = call ptr @a68rt_enter(i32 1, i32 0)
  %t653 = load i64, ptr %v215
  call void @a68rt_set_int(i32 0, i32 0, i64 %t653, i32 0)
  store i32 17, ptr @a68_line_no, !tbaa !16
  %t654 = call i64 @a68rt_cell_int(i32 0, i32 0, i32 0)
  store i64 %t654, ptr %v224
  %t655 = load ptr, ptr %v4
  %t656 = getelementptr i8, ptr %t655, i64 16
  %t657 = load i32, ptr %t656, !tbaa !11
  %t658 = zext i32 %t657 to i64
  store i64 %t658, ptr %v227
  %t659 = load i64, ptr %v227
  %t660 = icmp eq i64 %t659, 9
  store i1 %t660, ptr %v228
  %t661 = load i1, ptr %v228
  br i1 %t661, label %b99, label %b100
b95:
  %t662 = load i64, ptr %v3
  %t663 = icmp ne i64 %t662, 0
  store i1 %t663, ptr %v280
  %t664 = load i1, ptr %v280
  br i1 %t664, label %b124, label %b125
b96:
  %t665 = load i64, ptr %v215
  %t666 = add i64 %t665, 1
  %t667 = icmp sgt i64 %t666, 2147483647
  %t668 = icmp slt i64 %t666, -2147483647
  %t669 = or i1 %t667, %t668
  br i1 %t669, label %trap670, label %cont670
trap670:
  store i32 24, ptr @a68_line_no, !tbaa !16
  call void @a68rt_arith_error(i32 0, i32 0)
  unreachable
cont670:
  store i64 %t666, ptr %v279
  %t671 = load i64, ptr %v279
  store i64 %t671, ptr %v215
  br label %b93
b97:
  store i32 24, ptr @a68_line_no, !tbaa !16
  %t672 = load i64, ptr %v224
  %t673 = call i8 @a68rt_row_bool(i32 1, i32 1, i32 1, i64 %t672, i64 0, i32 0)
  %t674 = icmp ne i8 %t673, 0
  store i1 %t674, ptr %v267
  %t675 = load i1, ptr %v267
  store i1 %t675, ptr %v225
  br label %b98
b98:
  %t676 = load i1, ptr %v225
  br i1 %t676, label %b114, label %b115
b99:
  %t677 = load ptr, ptr %v4
  %t678 = getelementptr i8, ptr %t677, i64 24
  %t679 = load ptr, ptr %t678, !tbaa !11
  store ptr %t679, ptr %v229
  %t680 = load ptr, ptr %v229
  store ptr %t680, ptr %v226
  br label %b101
b100:
  %t681 = load i64, ptr %v227
  %t682 = icmp eq i64 %t681, 8
  store i1 %t682, ptr %v230
  %t683 = load i1, ptr %v230
  br i1 %t683, label %b102, label %b97
b101:
  %t684 = load ptr, ptr %v226
  %t685 = getelementptr i8, ptr %t684, i64 40
  %t686 = load i32, ptr %t685, !tbaa !12
  %t687 = zext i32 %t686 to i64
  store i64 %t687, ptr %v236
  %t688 = load i64, ptr %v236
  %t689 = icmp eq i64 %t688, 0
  store i1 %t689, ptr %v237
  %t690 = load i1, ptr %v237
  br i1 %t690, label %b105, label %b97
b102:
  %t691 = load ptr, ptr %v4
  %t692 = getelementptr i8, ptr %t691, i64 20
  %t693 = load i32, ptr %t692, !tbaa !11
  %t694 = zext i32 %t693 to i64
  store i64 %t694, ptr %v231
  %t695 = load i64, ptr %v231
  %t696 = icmp eq i64 %t695, 4294967295
  store i1 %t696, ptr %v232
  %t697 = load i1, ptr %v232
  br i1 %t697, label %b103, label %b97
b103:
  %t698 = load ptr, ptr %v4
  %t699 = getelementptr i8, ptr %t698, i64 24
  %t700 = load ptr, ptr %t699, !tbaa !11
  store ptr %t700, ptr %v233
  %t701 = load ptr, ptr %v233
  %t702 = getelementptr i8, ptr %t701, i64 0
  %t703 = load i8, ptr %t702, !tbaa !12
  %t704 = zext i8 %t703 to i64
  store i64 %t704, ptr %v234
  %t705 = load i64, ptr %v234
  %t706 = icmp eq i64 %t705, 3
  store i1 %t706, ptr %v235
  %t707 = load i1, ptr %v235
  br i1 %t707, label %b104, label %b97
b104:
  %t708 = load ptr, ptr %v233
  store ptr %t708, ptr %v226
  br label %b101
b105:
  %t709 = load ptr, ptr %v226
  %t710 = getelementptr i8, ptr %t709, i64 32
  %t711 = load i64, ptr %t710, !tbaa !12
  store i64 %t711, ptr %v238
  %t712 = load ptr, ptr %v226
  %t713 = getelementptr i8, ptr %t712, i64 48
  %t714 = load i64, ptr %t713, !tbaa !12
  store i64 %t714, ptr %v239
  %t715 = load ptr, ptr %v226
  %t716 = getelementptr i8, ptr %t715, i64 56
  %t717 = load i64, ptr %t716, !tbaa !12
  store i64 %t717, ptr %v240
  %t718 = load ptr, ptr %v226
  %t719 = getelementptr i8, ptr %t718, i64 64
  %t720 = load i64, ptr %t719, !tbaa !12
  store i64 %t720, ptr %v241
  %t721 = load i64, ptr %v224
  %t722 = load i64, ptr %v239
  %t723 = icmp sge i64 %t721, %t722
  store i1 %t723, ptr %v242
  %t724 = load i64, ptr %v224
  %t725 = load i64, ptr %v240
  %t726 = icmp sle i64 %t724, %t725
  store i1 %t726, ptr %v243
  %t727 = load i1, ptr %v242
  %t728 = load i1, ptr %v243
  %t729 = and i1 %t727, %t728
  store i1 %t729, ptr %v244
  %t730 = load i1, ptr %v244
  br i1 %t730, label %b107, label %b106
b106:
  store i32 24, ptr @a68_line_no, !tbaa !16
  %t731 = load i64, ptr %v224
  %t732 = load i64, ptr %v239
  %t733 = load i64, ptr %v240
  call void @a68rt_index_error(i64 %t731, i64 %t732, i64 %t733, i32 0)
  unreachable
b107:
  %t734 = load i64, ptr %v224
  %t735 = load i64, ptr %v239
  %t736 = sub i64 %t734, %t735
  store i64 %t736, ptr %v245
  %t737 = load i64, ptr %v245
  %t738 = load i64, ptr %v241
  %t739 = mul i64 %t737, %t738
  store i64 %t739, ptr %v246
  %t740 = load i64, ptr %v238
  %t741 = load i64, ptr %v246
  %t742 = add i64 %t740, %t741
  store i64 %t742, ptr %v247
  %t743 = load ptr, ptr %v226
  %t744 = getelementptr i8, ptr %t743, i64 24
  %t745 = load ptr, ptr %t744, !tbaa !12
  store ptr %t745, ptr %v248
  %t746 = load ptr, ptr %v248
  %t747 = getelementptr i8, ptr %t746, i64 0
  %t748 = load i8, ptr %t747, !tbaa !12
  %t749 = zext i8 %t748 to i64
  store i64 %t749, ptr %v249
  %t750 = load ptr, ptr %v248
  store ptr %t750, ptr %v250
  %t751 = load i64, ptr %v249
  %t752 = icmp eq i64 %t751, 3
  store i1 %t752, ptr %v251
  %t753 = load i1, ptr %v251
  br i1 %t753, label %b108, label %b109
b108:
  %t754 = load ptr, ptr %v248
  %t755 = getelementptr i8, ptr %t754, i64 24
  %t756 = load ptr, ptr %t755, !tbaa !12
  store ptr %t756, ptr %v252
  %t757 = load ptr, ptr %v252
  store ptr %t757, ptr %v250
  br label %b109
b109:
  %t758 = load ptr, ptr %v250
  %t759 = getelementptr i8, ptr %t758, i64 0
  %t760 = load i8, ptr %t759, !tbaa !12
  %t761 = zext i8 %t760 to i64
  store i64 %t761, ptr %v253
  %t762 = load i64, ptr %v253
  %t763 = icmp eq i64 %t762, 2
  store i1 %t763, ptr %v254
  %t764 = load i1, ptr %v254
  br i1 %t764, label %b110, label %b97
b110:
  %t765 = load ptr, ptr %v250
  %t766 = getelementptr i8, ptr %t765, i64 2
  %t767 = load i16, ptr %t766, !tbaa !12
  %t768 = zext i16 %t767 to i64
  store i64 %t768, ptr %v255
  %t769 = load i64, ptr %v255
  %t770 = icmp eq i64 %t769, 3
  store i1 %t770, ptr %v256
  %t771 = load i1, ptr %v256
  br i1 %t771, label %b111, label %b97
b111:
  %t772 = load ptr, ptr %v250
  %t773 = getelementptr i8, ptr %t772, i64 4
  %t774 = load i32, ptr %t773, !tbaa !12
  %t775 = zext i32 %t774 to i64
  store i64 %t775, ptr %v257
  %t776 = load i64, ptr %v257
  %t777 = mul i64 %t776, 1
  store i64 %t777, ptr %v258
  %t778 = load i64, ptr %v258
  %t779 = load i64, ptr %v247
  %t780 = add i64 %t778, %t779
  store i64 %t780, ptr %v259
  %t781 = load i64, ptr %v259
  %t782 = add i64 %t781, 24
  store i64 %t782, ptr %v260
  %t783 = load ptr, ptr %v250
  %t784 = load i64, ptr %v260
  %t785 = getelementptr i8, ptr %t783, i64 %t784
  %t786 = load i8, ptr %t785, !tbaa !13
  %t787 = zext i8 %t786 to i64
  store i64 %t787, ptr %v261
  %t788 = load i64, ptr %v261
  %t789 = icmp ne i64 %t788, 0
  store i1 %t789, ptr %v262
  %t790 = load i1, ptr %v262
  br i1 %t790, label %b113, label %b112
b112:
  store i32 24, ptr @a68_line_no, !tbaa !16
  call void @a68rt_undef_error(i32 2, i32 0)
  unreachable
b113:
  %t791 = load i64, ptr %v247
  %t792 = mul i64 %t791, 1
  store i64 %t792, ptr %v263
  %t793 = load i64, ptr %v263
  %t794 = add i64 %t793, 24
  store i64 %t794, ptr %v264
  %t795 = load ptr, ptr %v250
  %t796 = load i64, ptr %v264
  %t797 = getelementptr i8, ptr %t795, i64 %t796
  %t798 = load i8, ptr %t797, !tbaa !13
  %t799 = zext i8 %t798 to i64
  store i64 %t799, ptr %v265
  %t800 = load i64, ptr %v265
  %t801 = icmp ne i64 %t800, 0
  store i1 %t801, ptr %v266
  %t802 = load i1, ptr %v266
  store i1 %t802, ptr %v225
  br label %b98
b114:
  %t803 = load i64, ptr %v2
  %t804 = add i64 %t803, 1
  %t805 = icmp sgt i64 %t804, 2147483647
  %t806 = icmp slt i64 %t804, -2147483647
  %t807 = or i1 %t805, %t806
  br i1 %t807, label %trap808, label %cont808
trap808:
  store i32 18, ptr @a68_line_no, !tbaa !16
  call void @a68rt_arith_error(i32 0, i32 0)
  unreachable
cont808:
  store i64 %t804, ptr %v268
  %t809 = load i64, ptr %v268
  store i64 %t809, ptr %v2
  store i32 19, ptr @a68_line_no, !tbaa !16
  call void @a68rt_push_builtin(i32 0, i32 0)
  call void @a68rt_push_format(i32 3, i32 0)
  call void @a68rt_unite(i32 4, i32 0)
  %t810 = call i64 @a68rt_cell_int(i32 0, i32 0, i32 0)
  store i64 %t810, ptr %v269
  %t811 = load i64, ptr %v269
  call void @a68rt_push_int(i64 %t811, i32 0)
  call void @a68rt_unite(i32 5, i32 0)
  %t812 = zext i1 false to i8
  call void @a68rt_collateral(i32 2, i8 %t812, i32 1, i32 0)
  call void @a68rt_call(i32 1, i32 0)
  %t813 = load i32, ptr @a68_jump_flag
  store i32 %t813, ptr %v270
  %t814 = load i32, ptr %v270
  %t815 = icmp ne i32 %t814, 0
  store i1 %t815, ptr %v271
  %t816 = load i1, ptr %v271
  br i1 %t816, label %b117, label %b119
b115:
  br label %b116
b116:
  store i32 19, ptr @a68_line_no, !tbaa !16
  call void @a68rt_leave(i32 0)
  br label %b96
b117:
  %t817 = load i32, ptr @a68_jump_flag
  store i32 %t817, ptr %v272
  %t818 = load i32, ptr %v272
  %t819 = sub i32 %t818, 1
  store i32 %t819, ptr %v273
  %t820 = load i32, ptr %v273
  switch i32 %t820, label %b118 [  ]
b118:
  ret void
b119:
  store i32 19, ptr @a68_line_no, !tbaa !16
  call void @a68rt_pop(i32 0)
  %t821 = load i64, ptr %v3
  %t822 = add i64 %t821, 1
  %t823 = icmp sgt i64 %t822, 2147483647
  %t824 = icmp slt i64 %t822, -2147483647
  %t825 = or i1 %t823, %t824
  br i1 %t825, label %trap826, label %cont826
trap826:
  store i32 20, ptr @a68_line_no, !tbaa !16
  call void @a68rt_arith_error(i32 0, i32 0)
  unreachable
cont826:
  store i64 %t822, ptr %v274
  %t827 = load i64, ptr %v274
  store i64 %t827, ptr %v3
  %t828 = load i64, ptr %v274
  %t829 = icmp eq i64 %t828, 10
  store i1 %t829, ptr %v275
  %t830 = load i1, ptr %v275
  br i1 %t830, label %b120, label %b121
b120:
  store i32 21, ptr @a68_line_no, !tbaa !16
  call void @a68rt_push_builtin(i32 6, i32 0)
  call void @a68rt_push_builtin(i32 7, i32 0)
  call void @a68rt_unite(i32 11, i32 0)
  call void @a68rt_row_of(i32 0)
  call void @a68rt_call(i32 1, i32 0)
  %t831 = load i32, ptr @a68_jump_flag
  store i32 %t831, ptr %v276
  %t832 = load i32, ptr %v276
  %t833 = icmp ne i32 %t832, 0
  store i1 %t833, ptr %v277
  %t834 = load i1, ptr %v277
  br i1 %t834, label %b117, label %b123
b121:
  br label %b122
b122:
  br label %b116
b123:
  store i32 21, ptr @a68_line_no, !tbaa !16
  call void @a68rt_pop(i32 0)
  store i64 0, ptr %v3
  br label %b122
b124:
  store i32 24, ptr @a68_line_no, !tbaa !16
  call void @a68rt_push_builtin(i32 6, i32 0)
  call void @a68rt_push_builtin(i32 7, i32 0)
  call void @a68rt_unite(i32 11, i32 0)
  call void @a68rt_row_of(i32 0)
  call void @a68rt_call(i32 1, i32 0)
  %t835 = load i32, ptr @a68_jump_flag
  store i32 %t835, ptr %v281
  %t836 = load i32, ptr %v281
  %t837 = icmp ne i32 %t836, 0
  store i1 %t837, ptr %v282
  %t838 = load i1, ptr %v282
  br i1 %t838, label %b117, label %b127
b125:
  br label %b126
b126:
  store i32 25, ptr @a68_line_no, !tbaa !16
  call void @a68rt_push_builtin(i32 0, i32 0)
  call void @a68rt_push_format(i32 21, i32 0)
  call void @a68rt_unite(i32 4, i32 0)
  call void @a68rt_push_int(i64 100, i32 0)
  call void @a68rt_unite(i32 5, i32 0)
  %t839 = load i64, ptr %v2
  call void @a68rt_push_int(i64 %t839, i32 0)
  call void @a68rt_unite(i32 5, i32 0)
  %t840 = zext i1 false to i8
  call void @a68rt_collateral(i32 3, i8 %t840, i32 1, i32 0)
  call void @a68rt_call(i32 1, i32 0)
  %t841 = load i32, ptr @a68_jump_flag
  store i32 %t841, ptr %v283
  %t842 = load i32, ptr %v283
  %t843 = icmp ne i32 %t842, 0
  store i1 %t843, ptr %v284
  %t844 = load i1, ptr %v284
  br i1 %t844, label %b117, label %b128
b127:
  store i32 25, ptr @a68_line_no, !tbaa !16
  call void @a68rt_pop(i32 0)
  br label %b126
b128:
  br label %b1
}

define void @a68_hole0() {
entry:
  %v0 = alloca i64
  br label %b0
b0:
  store i64 0, ptr %v0
  br label %b1
b1:
  store i32 1, ptr @a68_line_no, !tbaa !16
  %t0 = load i64, ptr %v0
  call void @a68rt_push_int(i64 %t0, i32 0)
  ret void
}

define void @a68_hole1() {
entry:
  %v0 = alloca i64
  br label %b0
b0:
  store i64 0, ptr %v0
  br label %b1
b1:
  store i32 1, ptr @a68_line_no, !tbaa !16
  %t0 = load i64, ptr %v0
  call void @a68rt_push_int(i64 %t0, i32 0)
  ret void
}

define void @a68_dispatch_proc(i64 %fn) {
entry:
  switch i64 %fn, label %none [ i64 0, label %f0 ]
f0:
  call void @a68_fn0()
  ret void
none:
  ret void
}

define void @a68_dispatch_hole(i64 %idx) {
entry:
  switch i64 %idx, label %none [ i64 0, label %h0 i64 1, label %h1 ]
h0:
  call void @a68_hole0()
  ret void
h1:
  call void @a68_hole1()
  ret void
none:
  ret void
}

define i32 @main(i32 %argc, ptr %argv) {
entry:
  call void @a68rt_boot(ptr @A68_BLOB, i32 12, i8 0, i32 %argc, ptr %argv, ptr @A68_SRC)
  call void @a68_fn0()
  %rc = call i32 @a68rt_finish(i32 0)
  ret i32 %rc
}
!0 = !{!"a68 memory"}
!1 = !{!"a cell or a slot", !0}
!2 = !{!"a frame cell", !1}
!3 = !{!"a slot value", !1}
!4 = !{!"an object header", !0}
!5 = !{!"leaf data", !0}
!6 = !{!"the line number", !0}
!11 = !{!2, !2, i64 0}
!12 = !{!4, !4, i64 0}
!13 = !{!5, !5, i64 0}
!14 = !{!3, !3, i64 0}
!15 = !{!1, !1, i64 0}
!16 = !{!6, !6, i64 0}